### ISSUE TITLE
annotation file

### ISSUE THREAD

**Issue by jflucier** [LabTranslationalArchitectomics/riboWaltz#1]
Hello,

i would like to try out riboWaltz. Is there an easy way to generate the annotation file using gtf file downloaded from ensembl.

tks

JF

**Comment by fabiolauria** [comment]
Hi,

the answer unfortunately is no. The annotation file  provided in the example was generated starting from a GTF from gencode and manually computing the length of the three regions on the basis of the exsons length. To solve this issue we are currently working on a new function for generating the required annotation file directly from a GTF file.
Meanwhile the functions makeTxDbFromGFF, cdsBy, fiveUTRsByTranscript and threeUTRsByTranscript from the GenomicFeatures package can be of some help.

Bests
Fabio

**Comment by jflucier** [comment]
tks for answering back. I will take a look at the genomicfeature package.

JF

**Comment by tmargus** [comment]
Hi,

I have similar problem converting ensembl's GTF to annotation file. I wonder do you solved this problem?

Cheers,
TM

**Comment by fabiolauria** [comment]
Hi,
we solved this problem by adding the create_annotation function that takes as input a GTF file or a TxDb object and returns a data frame with the required information. As previously mentioned, it is based on the GenomicFeature package.

Bests,
Fabio
