### ISSUE TITLE
bamtolist confusion

### ISSUE THREAD

**Issue by bontus** [LabTranslationalArchitectomics/riboWaltz#14]
Hi Fabio,

I have noticed that bamtolist filtered out a lot of reads based on "mapping on the negative strand" even though the reads were clearly in (+) direction, so I checked the function code and noticed that the transcript names of the annotation and the mapping coordinates are also compared in the same step, and if no match can be found the reads are discarded. In my opinion, this is misleading, as the reads are not discarded based on their strandedness but because the annotation is incorrect.

Hence, I would modify this piece of code:

```
if (transcript_align == TRUE | transcript_align == T) {
    nreads <- nrow(dt)
    cat(sprintf("reads (total): %s M\n", format(round((nreads/1e+06), 
        2), nsmall = 2)))
    dt <- dt[as.character(transcript) %in% as.character(annotation$transcript) & 
        strand == "+"]
    cat(sprintf("%s M  (%s %%) reads removed: mapping on the negative strand\n", 
        format(round((nreads - nrow(dt))/1e+06, 2), nsmall = 2), 
        format(round(((nreads - nrow(dt))/nreads) * 100, 
        2), nsmall = 2)))
}
```
and make it two steps to clearly separate the two
```
# Filter based on annotation
dt <- dt[as.character(transcript) %in% as.character(annotation$transcript)]
# Filter based on strand
dt <- dt[strand == "+"]
```
or alternatively, output the corresponding numbers for both steps.

Best

**Comment by fabiolauria** [comment]
Hi Bontus,
thanks for the tip.
I guess you are using an out-of-date version of _bamtolist_. I have already received a similar comment [(here)](https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/9) and I have modified the function accordingly. Now it throws two messages, one for the IDs and one for strand.

Bests,
Fabio
