### ISSUE TITLE
metaprofile stop codon peak

### ISSUE THREAD

**Issue by hollyjaro** [LabTranslationalArchitectomics/riboWaltz#19]
Hello,

first of all I would like to say that the riboWaltz is a great package for ribo-seq and I really enjoy using it. I just want to clarify some features in metaprofile plot, specifically the stop codon part. Does the "0" on the plot corresponds to the last nucleotide of stop codon like on the attached picture? And the red line represents end of the CDS including the STOP codon?
<img width="606" alt="Screen Shot 2019-03-12 at 1 53 27 PM" src="https://user-images.githubusercontent.com/46112452/54225104-55cf1880-44d1-11e9-8d87-f379d73abebb.png">

Usually the stop codon is not considered as part of the CDS so it's a little bit confusing as the the "stop" peak is really strong in my data and it's "far" from the "stop" red line. As for the translation termination the p-site should not reach the stop codon I would expect the peak to be on the second codon to the last one, the last one to be STOP codon. In the manual you write that the p-sites are plotted on the leftmost position so it would make sense for me be as it is on the picture.

Thanks in advance!

**Comment by fabiolauria** [comment]
Hi,
thank you for using riboWaltz.

You are right, the 0 correspond to (the beginning of) the last nucleotide of CDSs. This means the red line is the very end of the CDSs. I know the it might result a bit confusing, but I choose this notation and visualization for convenience in the writing of the code and for sake of consistency with the notation and visualization adopted for the start codon.

This means the peak above is on the second to last codon, the one before the stop codon. I'm not sure I fully understood your comments about what you would expect to see in the metaprofile: do we agree that if the 0 is the stop codon (and, as I said, it is) so the peak you observe is in the correct position? By the way, this is the reason why the **psite** function allows to use as reference codon the start codon or _the second to last codon_. 

Please let me know if I answer to your question properly, dispelling your doubts. If not, I'll try to better explain this point.

Bests,
Fabio

**Comment by hollyjaro** [comment]
Hi Fabio,

thanks for the prompt response. I got it now and it is exactly as I thought. Thanks for doing great work in this topic! I have other questions related to other functions of riboWaltz but I will submit it later as a new issue.

Thanks!
Best,

Jaro
