### ISSUE TITLE
Unable to get riboWaltz to read annotation sequences

### ISSUE THREAD

**Issue by jalalsiddiqui** [LabTranslationalArchitectomics/riboWaltz#20]
I aligned Ribo profiling data using Bowtie1 indices derived from hg38 fasta files from Ensembl.  I have gotten featureCounts to work via the hg28 gtf files however I get this error:

(100.00 %) reads removed: reference transcript IDs not found in annotation table.

Do you know how I can go about this?

**Comment by fabiolauria** [comment]
Hi Jalal.
Are you talking about function _bamtolist_, right? If so, it seems there is a discrepancy between the **transcript** names in the annotation data.table (as they are returned by _create_annotation _) and the reference names of the sequences in the BAM file. Are the latter transcript or gene names? About this, please read carefully the [remark](https://github.com/LabTranslationalArchitectomics/riboWaltz#remark) section in the riboWaltz's homepage.
Unfortunately, featureCounts working on you dataset doesn't necessarily mean riboWaltz will work with the same inputs: there is no connection between the tools and they require different files.

Bests,
Fabio

**Comment by jalalsiddiqui** [comment]
Hi Fabio,


I am talking about the bamtolist function.  I do see your point and notice the different.  I looked at the .bam files and saw the difference in annnotation IDs and I think have solved this problem.  I will get back to you if I still have trouble.


Thanks,



Jalal

________________________________

**Comment by jalalsiddiqui** [comment]
I checked.  The latter were transcript names.  Could that be the problem?  I know you prefer aligmnents to the transcriptome?

Jalal

From: "Siddiqui, Jalal" <Jalal.Siddiqui@osumc.edu>
Date: Sunday, May 19, 2019 at 5:39 PM
To: LabTranslationalArchitectomics/riboWaltz <riboWaltz@noreply.github.com>, LabTranslationalArchitectomics/riboWaltz <reply@reply.github.com>
Cc: "Jalal K. Siddiqui" <siddiqui.13@osu.edu>, Author <author@noreply.github.com>
Subject: Re: [LabTranslationalArchitectomics/riboWaltz] Unable to get riboWaltz to read annotation sequences (#20)
Resent-From: <siddiqui.13@osu.edu>
Resent-Date: Sunday, May 19, 2019 at 5:39 PM


Hi Fabio,



I am talking about the bamtolist function.  I do see your point and notice the different.  I looked at the .bam files and saw the difference in annnotation IDs and I think have solved this problem.  I will get back to you if I still have trouble.



Thanks,





Jalal

________________________________

**Comment by fabiolauria** [comment]
Hi Jalal.
I'm sorry but I'm lost. To make things clear:
- does the annotation data.table from _create_annotation_ contain transcript names? I guess so.
- are the BAM files based on transcript coordinates i.e. are their reference sequences named after transcript IDs?

If the answer to both questions is "yes", is it possible the name of the transcripts in the two files is different (e.g. only one of the two reports transcripts version. About this, see parameter _refseq_sep_ of function _bamtolist_)?
Would it be possible for you to include in the next message the first 5 lines of the annotation data.table and of one of your BAM files, as they are returned by the alignment process? It would be of great help.

By the way, aligning to the transcriptome is not a requirement for riboWaltz to work properly, even if it would simplify all the sequence-based analyses. You can also align against chromosome sequences, as long as the BAM files will be based on transcript coordinates.

Bests
Fabio

**Comment by jalalsiddiqui** [comment]
Sorry about this.

Here are the first few lines of the bam file aligned to the genome:

K00124:310:HTNTNBBXX:1:1210:26981:45523    0              1              22093    255         115M    *              0              0                GTCATAGTCCCCTGGCCCCATTAATGGATTCTGGGATAGACATGAGGACCAAGCCAGGTGGGATGAGTGAGTGTGGCTTCTGGAGGAAGTGGGGACACAGGACAGCATTCTTTCC                AFFFJFFFJJFJJFAJFJJAJFJJJFJJJJ<<FF-FAJFJFFJJF-FAJJFJFJJFJ<7JJJ-FJ<AAAJFJJF<FJFFFJJJJJJJJJA7AFJFJ<JFJFJJJJ<JFAJJJFAJ         XA:i:0    MD:Z:115            NM:i:0
K00124:310:HTNTNBBXX:1:1123:23490:67252    0              1              22414    255         82M       *              0              0                CCACCAATTCTTACCGATTTCTCTCCACTCTAGACCCTGAGAAGCCCACGCGGTTCATGCTAGCAATTAACAATCAATCTCG                AFFFJJFJJJJJJJJJJJJJFJJJJJJJJJJJJFJJJJJJJJJAJJAFJJJFJJFJJJJFAJJJJ7FJFJFJ<FFJJJAJJF             XA:i:0    MD:Z:82                NM:i:0
K00124:310:HTNTNBBXX:1:1212:13139:39827    0              1              140098 255         15M       *              0              0                GCTCCATGGCTCAGG       AFFFJJJJJJJJFJJ     XA:i:0    MD:Z:15               NM:i:0
K00124:310:HTNTNBBXX:1:1212:14326:68043    16           1              159698 255         20M       *              0              0                ACTCCCAAATAGTTCGACTC           JFJJJJJJJAJJJJJJFFFA            XA:i:2    MD:Z:9C9G0       NM:i:2
K00124:310:HTNTNBBXX:1:1123:31426:10539    16           1              258552 255         24M       *              0              0                GACTCAGTTTAGATGGTCCCAATT                JFJJFJJJJJJJAJJJJJFJFFFA    XA:i:2    MD:Z:12G2A8    NM:i:2

Here are the bam file aligned to the transcriptome

K00124:310:HTNTNBBXX:1:2203:15321:42552    16           ENST00000390423.2       266         255         16M       *              0                0              CACATCTGTCTTACAA      F<JFFJJJJJJJFFAA XA:i:2    MD:Z:2T0T12     NM:i:2
K00124:310:HTNTNBBXX:1:2102:16955:10328    0              ENST00000390348.2       395         255         16M       *              0                0              ATTGGAATTTGAGACT     AFFFJJFJFJJJJJJJ  XA:i:0    MD:Z:16               NM:i:0
K00124:310:HTNTNBBXX:1:1105:22688:68570    0              ENST00000444775.2       274         255         14M       *              0                0              GAAATGTTTAGGAC         AFFFJJJJJJJJJJ       XA:i:0    MD:Z:14               NM:i:0
K00124:310:HTNTNBBXX:1:1106:6816:66847      0              ENST00000444775.2       274         255         14M       *              0                0              GAAATGTTTAGGAC         AFFFJJJJJJJJJJ       XA:i:0    MD:Z:14               NM:i:0
K00124:310:HTNTNBBXX:1:1214:21034:37190    0              ENST00000444775.2       274         255         14M       *              0                0              GAAATGTTTAGGAC         AFFFJJJJJJJJJJ       XA:i:0    MD:Z:14               NM:i:0

Here are the first few lines of the annotation data frame created using the create_annotation function.

        transcript l_tr l_utr5 l_cds l_utr3
1: ENST00000000233 1032     88   543    401
2: ENST00000000412 2450    159   834   1457
3: ENST00000000442 2274    225  1272    777
4: ENST00000001008 3715    170  1380   2165
5: ENST00000001146 4732    204  1539   2989
6: ENST00000002125 2184     48  1326    810

Hope this helps,



Jalal

**Comment by fabiolauria** [comment]
Hi Jalal.

As expected, the problem arises because of the different reference ID stored in the two files: the annotation file contains common Ensembl-based names (e.g. ENST00000000233), while the BAM file reports long strings (e.g. K00124:310:HTNTNBBXX:1:2203:15321:42552).

I don't know where the latter ID come from, but there are two options I can think of: 1) the FASTA file used in the alignment process contains this type of **transcript** IDs as sequences header, that are not compatible with the ENST symbols; 2) the alignment was not performed on transcripts and the BAM files are not based on transcript coordinates. Both cases, I'm sorry to say riboWaltz cannot work properly.

As general advice, I would suggest you to use bowtie2 using transcript FASTA files (have a look to GENCODE for this) or, even better, STAR aligner.

Bests,
Fabio

**Comment by jalalsiddiqui** [comment]
Thanks Fabio

You mean stuff from here:

https://www.gencodegenes.org/human/

I can get the transcript sequences for the fasta file and what gtf file will you recommend?

I plan on using the STAR aligner for the ribosomal profiling data.

Thanks,


Jalal

**Comment by fabiolauria** [comment]
Hi Jalal.

The GENCODE repository is the one you reported above. There are two options:

1) use STAR aligning on FASTA files containing "Genome sequence" and GTF labeled with "Comprehensive gene annotation" **that is required by STAR**. Using option _--quantMode TranscriptomeSAM_ when running STAR you would get two BAM files for each sample: one based on chromosome coordinates and one based on transcript coordinates . The latter can be used as input in function _bamtolist_ from riboWaltz (setting "transcript_align = FALSE").
2) if you do not need the BAM file based on chromosome coordinates, you can use the FASTA file with "Transcript sequence" using Bowtie2 (I'm not familiar with Bowtie1 but it may work just fine). Although in this case you wouldn't need any GTF file for the alignment step, it would be required for riboWaltz (again, the one labeled with "Comprehensive gene annotation" would be fine).

It's up to you. Keep in mind that STAR is faster than Bowtie2 once you have generated the required indexes. Unfortunately, I think you cannot use STAR with FASTA of transcript sequences because, as I mentioned before, STAR requires specific GTF files and there is no GTF based on transcripts (at least in GENCODE).

Bests,
Fabio

**Comment by jalalsiddiqui** [comment]
Thanks for the help.  We originally had used Bowtie1 as it might work better for shorter sequences.  I can also shift to STAR as well.


I can try this:


1.  Use the GENECODE link and use that Fasta file for the transcriptome to align using Bowtie1 as we have done


2.  Redo the alignment with the GENECODE Genome sequences using STAR aligner and follow this


Let me try these and I will get back to you...


Jalal

________________________________

**Comment by jalalsiddiqui** [comment]
I reran the alignments using Bowtie1 (I had been using that due to it working for smaller reads) using the GTF files obtained from GENCODE.  

The first lines of the annotation object from RiboWaltz are as follows:

           transcript l_tr l_utr5 l_cds l_utr3
1: ENST00000000233.10 1032     88   543    401
2:  ENST00000000412.8 2450    159   834   1457
3: ENST00000000442.11 2274    225  1272    777
4:  ENST00000001008.6 3715    170  1380   2165
5:  ENST00000001146.6 4732    204  1539   2989
6:  ENST00000002125.9 2184     48  1326    810

I reran using the fasta file from GENCODE and got the following bam file.  

K00124:425:H23H2BBXX:3:1206:6289:33902	16	ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-202|DDX11L1|1657|processed_transcript|	986	255	19M	*	00	TCTTCCATCCTTCTTGGCC	JJFJJJJJJJJJJJJFFFA	XA:i:2	MD:Z:11G1G5	NM:i:2
K00124:425:H23H2BBXX:3:2209:14864:53996	0	ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|	44	255	30M	*	00	TGACTCCTGTGAGGATGCAGCACTCCCTGG	AFFFJJJJJJJJJJJJJJJJJJJJJJJJJJ	XA:i:0	MD:Z:30	NM:i:0
K00124:425:H23H2BBXX:3:1204:10581:5933	0	ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|	47	255	28M	*	00	CTCCTGTGAGGATGCAGCACTCCCTGGC	AFFFJJJJJJJJJJJJJJJJJJJJJJJJ	XA:i:0	MD:Z:28	NM:i:0
K00124:425:H23H2BBXX:3:2103:29985:14055	0	ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|	343	255	29M	*	00	CCATCTTCACCGGCGCCCAGGACCCTGGC	AFFFJJJJJJJJJJJJJJJJJJJJJJJJJ	XA:i:1	MD:Z:10G18	NM:i:1
K00124:425:H23H2BBXX:3:2113:17807:55895	0	ENST00000488147.1|ENSG00000227232.5|OTTHUMG00000000958.1|OTTHUMT00000002839.1|WASH7P-201|WASH7P|1351|unprocessed_pseudogene|	343	255	29M	*	00	CCATCTTCACGGGCGCCCAGGACCCTGGC	AFFFJJJJJJJJJJJJJJJJJJJJJJJJJ	XA:i:0	MD:Z:29	NM:i:0

This of course didn't work due to the additional annotations which I then truncated from the fasta file and realigned and got this resulting bam file.  

K00124:425:H23H2BBXX:3:1206:6289:33902	16	ENST00000456328.2	986	255	19M	*	0	0	TCTTCCATCCTTCTTGGCC	JJFJJJJJJJJJJJJFFFA	XA:i:2	MD:Z:11G1G5	NM:i:2
K00124:425:H23H2BBXX:3:2209:14864:53996	0	ENST00000488147.1	44	255	30M	*	0	0	TGACTCCTGTGAGGATGCAGCACTCCCTGG	AFFFJJJJJJJJJJJJJJJJJJJJJJJJJJ	XA:i:0	MD:Z:30	NM:i:0
K00124:425:H23H2BBXX:3:1204:10581:5933	0	ENST00000488147.1	47	255	28M	*	0	0	CTCCTGTGAGGATGCAGCACTCCCTGGC	AFFFJJJJJJJJJJJJJJJJJJJJJJJJ	XA:i:0	MD:Z:28	NM:i:0
K00124:425:H23H2BBXX:3:2103:29985:14055	0	ENST00000488147.1	343	255	29M	*	0	0	CCATCTTCACCGGCGCCCAGGACCCTGGC	AFFFJJJJJJJJJJJJJJJJJJJJJJJJJ	XA:i:1	MD:Z:10G18	NM:i:1
K00124:425:H23H2BBXX:3:2113:17807:55895	0	ENST00000488147.1	343	255	29M	*	0	0	CCATCTTCACGGGCGCCCAGGACCCTGGC	AFFFJJJJJJJJJJJJJJJJJJJJJJJJJ	XA:i:0	MD:Z:29	NM:i:0

This did fortunately work!

I got the following lines

Good! Number of indel below indel_threshold for all reads. No reads removed.
reads: 30.00 M
Great! All reads' reference transcript IDs were found in annotation table. No reads removed.
0.57 M  (1.90 %) reads removed: mapping on negative strand.

However it does not appear to be finding the CDS

Here are the first few lines of the resulting object

   transcript end5 end3 length cds_start cds_stop
       1: ENST00000488147.1   44   73     30         0        0
       2: ENST00000488147.1   47   74     28         0        0
       3: ENST00000488147.1  343  371     29         0        0
       4: ENST00000488147.1  343  371     29         0        0
       5: ENST00000488147.1  343  370     28         0        0
      ---                                                      
29433539: ENST00000387461.2   43   68     26         0        0
29433540: ENST00000387461.2   45   67     23         0        0
29433541: ENST00000387461.2   45   67     23         0        0
29433542: ENST00000387461.2   46   67     22         0        0
29433543: ENST00000387461.2   53   68     16         0        0

The CDS is 0 for all of them.  Do you know why that would be the case?

I am thinking of realigning with Bowtie2 or even STAR?

Thanks for all your help,



Jalal

**Comment by fabiolauria** [comment]
Hi Jalal.
I'm happy to hear something is moving on.

Regarding the the coding sequences, did you verify all of them are actually of length 0? The two transcripts reported in your post are of biotype unprocessed pseudogene and MT tRNA, respectively. Since no CDS is annotated, _cds_start_ and _cds_stop_ are set to 0. What about the others? I hope

Two comments:
1) I don't think using Bowtie1 is a problem at all, but in my experience STAR (or Bowtie2) is good as well for short reads.
2) Note that to save the users from either manually modify the BAM files or, as you did, the FASTA file because of plentiful header annotation, _bamtolist_ provides the parameter **refseq_sep**. From _bamtolist_ documentation: 
**refseq_sep** is intended to lighten the identifiers of the reference sequences included in the output list of data table or modifying them to match those in the annotation table. Many details about the reference sequence such as their version (usually dot-separated), their length, name variants, associated gene/transcript/protein names (usually pipe-separated) might indeed be stored in the FASTA file used for the alignment and automatically transferred in the BAM.

Bests
Fabio

**Comment by jalalsiddiqui** [comment]
Thanks for all your help.  It works now.  I also got the results to work.  

As for the coding sequences I did find that many were not all zero.  Plus I forgot you had to use the _psite_info_ function to add the psite info to the reads.  That solved the problem.  

I did notice one warning when creating the annotation object:

_import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type stop_codon. This information was
  ignored._

Hopefully that should not be a problem.  

Anyways I think it is working now.  The only other thing I will end up doing is just trying STAR as it seems to be the preferred tool on your end for alignments.  That may be better to do now for the pipeline.

**Comment by fabiolauria** [comment]
Hi Jalal.
Good, finally everything is working.

The warning threw by the _psite_info_ function is a common message, but not an issue.
Regarding STAR, I'm prone to use it for two reasons: its fast and can give you both genome and transcriptome alignments at once. But it is only my personal opinion, Bowtie is good enough and I used it for years. 

Bests,
Fabio
