### ISSUE TITLE
Conda package request

### ISSUE THREAD

**Issue by bgruening** [LabTranslationalArchitectomics/riboWaltz#21]
Hi,

the Galaxy project got recently a request to include riboWaltz :)
A great first step would be a Canda package, e.g. https://bioconda.github.io or https://conda-forge.org.

Are there any plans to support such packages from upstream?

Thanks,
Bjoern

**Comment by fabiolauria** [comment]
Hi  Bjoern,
thabbroank you for contacting me and sorry for the delay.
I must inform you that I'm not familiar with Bioconda, Conda-forge and, generally speaking, with Python. Nevertheless, I carefully read the instructions about how to contribute to Bioconda. I'll try to approach the first steps in the near future, but I cannot assure rapid and successful results.
Hope this won't be a problem.

Bests,
Fabio

**Comment by heylf** [comment]
I am currently working on a conda recipe for this tool.

**Comment by heylf** [comment]
It is now available through conda. Maybe you want to update the README for conda installation.
