### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by Sinevadada** [LabTranslationalArchitectomics/riboWaltz#23]
Hi!
I have just started to use riboWaltz and I have a problem already with the first command.
I run
`reads_list <- bamtolist(bamfolder = path_bam, annotation)`
The error, that I get is:
Error: $ operator is invalid for atomic vectors.

**Comment by fabiolauria** [comment]
Hi.
This is strange, to my knowledge, many people menaged to run the current version of bamtolist without any error. Let me check the code and see what I find out.
Meanwhile, could you please post the complete command you run? Did you align on the genome requiring output BAMs to be in transcript coordinates or did you align directly on the transcriptome?

Bests,
Fabio

**Comment by Sinevadada** [comment]
Thank you very much for your reply!
I found out that the problem is with my BAM files. I made them using hisat2 and apparently there are no ensemblIDs in them. I guess it is only possible to use riboWaltz, if you made BAM files using STAR (I am working with a human data). I will try to make new BAM files.

**Comment by fabiolauria** [comment]
Actually it is not mandatory to align with STAR or Bowtie. You can use whatever you like, as long as the resulting BAM files are based on transcript coordinates. Obviously, the transcript IDs in the BAM files should match the ones in the annotation data table (that, if not generated by _create_annotation_ from starndard GTFs can be easily generated by the user in other ways).

**Comment by Sinevadada** [comment]
Thank you! 
I now think my issue is similar to [https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/9](url)
I used the same versions of Human gtf file and cdna.fasta file for create_annotation function and hisat2 alignment. Both files I downloaded from ENSEMBL. But unfortunately, the IDs don't match. 

Here is my BAM file:
NB551333:196:H3WKGBGXC:2:13311:10431:16447	256	ENST00000396859.5	380	1	37M	*	0	0	GTCTTCACCACCATGGAGAAGGCTGGGGCTCATTTGC	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	AS:i:0	ZS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:37	YT:Z:UU	XS:A:+	NH:i:5
NB551333:196:H3WKGBGXC:2:22102:12884:19872	256	ENST00000396859.5	380	1	34M	*	0	0	GTCTTCACCACCATGGAGAAGGCTGGGGCTCATT	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAS:i:0	ZS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:34	YT:Z:UU	XS:A:+	NH:i:5
NB551333:196:H3WKGBGXC:2:22211:7669:9500	0	ENST00000396859.5	380	1	35M	*	0	0	GTCTTCACCACCATGGAGAAGGCTGGGGCTCATTT	AAAAAEEEEEEAEEAA/AEEEEEE/EAEAAEEEE<	AS:i:0	ZS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:35	YT:Z:UU	XS:A:+	NH:i:5

And here is my annotation file:
91: ENST00000019019  1986    429   984    573
 92: ENST00000019103  1865    268  1323    274
 93: ENST00000019317  4368    223  1968   2177
 94: ENST00000020673  3824    168  3075    581
 95: ENST00000020926  5165    134  1281   3750
 96: ENST00000020945  2180    164   807   1209
 97: ENST00000022615  1418     91   852    475
 98: ENST00000023064  1766    193  1464    109

**Comment by fabiolauria** [comment]
Your issue is a bit more complicated since the IDs don't match not only because of the version of the transcripts, dot-separated, but because the Ensembl IDs in the BAM file are stored as additional information in the middle of the header. Unfortunately riboWaltz doesn't provide any option to extract a portion of the header.
I can suggest you to manually modify the BAM keeping only the third element of each header (using the space or tab as separator) and then import it in R using riboWaltz. Otherwise you can align again using either another tool, another reference FASTA or an option (if it exists) in order to get the original IDs as first information in the headers.

**Comment by Sinevadada** [comment]
Thank you. That's not an option for me, because I can't modify BAM files. I am giving a try to STAR-generated files.

**Comment by fabiolauria** [comment]
Hi,
I guess you have cleared your doubts so I'm closing this issue for now.
If you need some more help please don't hesitate to contact me again.

Bests
Fabio
