### ISSUE TITLE
codon_usage_psite error 

### ISSUE THREAD

**Issue by AlexFryd** [LabTranslationalArchitectomics/riboWaltz#24]
Hello !!!

I started using riboWaltz a week ago!!! Thanks a lot for such a nice tool!!

I am having a problem when introducing the fasta file for functions like _codon_usage_psite_ as I am getting this error: 

> Error: subscript contains invalid names

> 

I was following a similar issue from another issue (#16 If I recall) and in my case I tried to run the commands you highlighted:
name_tr <- unique(reads_psite_list[[SAMPLE_NAME]]$transcript)
sequences <- Biostrings::readDNAStringSet(YOUR_FASTA, format = "fasta", use.names = TRUE)
name_seq <- names(sequences)
table(name_tr %in% name_seq)

**I am getting the following:**
> table(name_tr %in% name_seq)
FALSE   TRUE
13616 129580

> 

I am new to R so I have been struggling to find out what I can do to extract the TRUE values and create a new table with only the matching transcript IDs.

Is there something I can do to make it work?

Thank  you in advance!

Kind Regards.
Alex

**Comment by fabiolauria** [comment]
Hi Alex,
thank you for using riboWaltz.
I know the function  _codon_usage_psite_ is a bit tricky and issues related to non-matching IDs keep arising. So, before going too far and manipulating your data, could you please send me the line you used for running _codon_usage_psite_, with all the parameters you specified? Plus, I need some additional information:
- did you align on transcript or chromosome sequences?
- the FASTA you gave as input for _codon_usage_psite_ is the same you had used for the alignment (not just the same version or from the same repository, I mean the very same)?

Bests,
Fabio

**Comment by AlexFryd** [comment]
Hello Fabio,

The line I used is as follows:

> NI810_codon_usage_ <- codon_usage_psite(filtered_list, annotation_dt (made with _create_annotation (gtf, version 97), sample = "NI810_deduplicated.tr", fastapath = "path/to//FASTA/file", fasta_genome = FALSE, frequency_normalization = FALSE) 

We aligned to genome, using  STAR aligner with the _quantMode_ TranscriptomeSAM option. Here is the code:

`STAR --runThreadN 20 --genomeDir /path/to/hg38.v97/  --readFilesIn NI810umi_ncRNAremoved.fq.gz --outSAMattributes All --quantMode TranscriptomeSAM --outFilterMismatchNmax 2 --alignEndsType EndToEnd --outFilterIntronMotifs RemoveNoncanonicalUnannotated --alignIntronMax 20000 --outMultimapperOrder Random --outSAMmultNmax 1  --outFileNamePrefix star/NI810 --outSAMtype BAM SortedByCoordinate --readFilesCommand zcat &>star/NI810_quant.star.log &`

The FASTA file I used for the _codon_usage_psite is indeed different compared to the one that I used for the alignment, as  for the _codon_psite_usage I used a cdna.fasta after manipulating the header so that it contains only the transcript ID  and the sequence, as it was consulted on issue #16.

Hope this helps.

Kind Regards,
Alex

**Comment by fabiolauria** [comment]
Hi Alex.
Thank you for your explanation.

> The FASTA file I used for the _codon_usage_psite is indeed different compared to the one that I used for the alignment, as for the _codon_psite_usage I used a cdna.fasta after manipulating the header so that it contains only the transcript ID and the sequence, as it was consulted on issue

This might be the main issue here.  If I understand correctly, you modify the IDs in the header of a FASTA that contains the sequences of cDNA (thus different from the one used for the alignment) . If so, you are using the wrong file. You should use the "original" FASTA (with chromosome sequences) and, in _codon_psite_usage, specify the parameters _fasta_genome_ = TRUE  and _gtfpath_ = "path/to/the/GTF/used/in/the/alignment.gtf".

Note: sometimes the names of the chromosomes in the FASTA and in the GTF are slightly different (i.e. chr1 vs chr1 1, chr2 vs chr2 2 etc). It is still a mismatch between names. If so, you can specify  _refseq_sep_ = " " (a space) for solving the problem. To verify possible difference between the chromosome names you can either manually open and inspect your files or run

```
library(data.table)

gtf_file <- "path/to/the/GTF/used/in/the/alignment.gtf"

txdbanno <- GenomicFeatures::makeTxDbFromGFF(file = gtf_file, format = "gtf")
exon <- suppressWarnings(GenomicFeatures::exonsBy(txdbanno, by = "tx", use.names = TRUE))
exon <- as.data.table(exon[unique(names(exon))])

human_pc_fasta <- "path/to/the/FASTA/used/in/the/alignment.fa"
temp_sequences <- Biostrings::readDNAStringSet(human_pc_fasta, format = "fasta", use.names = TRUE)

head(as.character(unique(exon$seqnames)))
head(names(temp_sequences))
```

I'm trying to find a way for automatically inferring the correct symbol for the _refseq_sep_ parameter. Otherwise it may be hard to find out.

Let me know if everything is clear.

Bests
Fabio

**Comment by AlexFryd** [comment]
Hello Fabio,

I already tried to use the correct fasta to re-rerun the function, and after your remarks, I also added the parameter _fasta_genome_=_TRUE_.

Here is the line:

> NI810_codon_usage <- codon_usage_psite (NI810_psites_list, annotation_dt, sample = "NI810_deduplicated.tr", fastapath="path/to/alignment/fasta/genome_clean_v97.fa", fasta_genome=TRUE, gtfpath="/path/to/gtf/Homo_sapiens.GRCh38.97.gtf")

> 

I do not know if it is necessary to use both the _annotation_dt made with_create_annotation and the _gtfpath_ parameter so I used both, and also seperately, Unfortunately I still get this:

> Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error: subscript contains invalid names

> 

Don't know if it matters, but here is what my psites_list looks like for my sample:
           
```

 transcript end5 psite end3 length cds_start cds_stop
       1: ENST00000450305  246   260  276     31         0        0
       2: ENST00000488147   38    52   65     28         0        0
       3: ENST00000488147   38    52   67     30         0        0
       4: ENST00000488147   38    52   67     30         0        0
       5: ENST00000488147   38    52   67     30         0        0
      ---
83650590: ENST00000616361 2715  2729 2745     31       174     2546
83650591: ENST00000616361 2769  2783 2799     31       174     2546
83650592: ENST00000616361 2832  2846 2859     28       174     2546
83650593: ENST00000616361 2837  2851 2867     31       174     2546
83650594: ENST00000616361 2848  2862 2877     30       174     2546
          
psite_from_start psite_from_stop psite_region
       1:                0               0         <NA>
       2:                0               0         <NA>
       3:                0               0         <NA>
       4:                0               0         <NA>
       5:                0               0         <NA>
      ---
83650590:             2555             183         3utr
83650591:             2609             237         3utr
83650592:             2672             300         3utr
83650593:             2677             305         3utr
83650594:             2688             316         3utr
```



Sorry for the length of the response, I hope I am at least providing something that can lead to a solution.

Kind Regards,
Alex

**Comment by fabiolauria** [comment]
Hi Alex,
sorry for the delay.
You are right, the _annotation_dt_ and the _gtfpath_ are both necessary. However, as specified in my previous comment, you might need to use **refseq_sep** due to potential mismatches between chromosome IDs. As suggested above, run the following code chunk and choose the correct **refseq_sep** symbol (if any) according to the results of the last two lines:

```
library(data.table)

gtf_file <- "path/to/the/GTF/used/in/the/alignment.gtf"

txdbanno <- GenomicFeatures::makeTxDbFromGFF(file = gtf_file, format = "gtf")
exon <- suppressWarnings(GenomicFeatures::exonsBy(txdbanno, by = "tx", use.names = TRUE))
exon <- as.data.table(exon[unique(names(exon))])

fasta_file <- "path/to/the/FASTA/used/in/the/alignment.fa"
temp_sequences <- Biostrings::readDNAStringSet(fasta_file, format = "fasta", use.names = TRUE)

head(as.character(unique(exon$seqnames)))
head(names(temp_sequences))
```

Bests,
Fabio

**Comment by AlexFryd** [comment]
Hello Fabio,

I did not use the chuck of lines before, as in both my .gtf and .fa files the chromosome annotation is "1" , "2" etc. In any case I run it and I got this:

> > head(as.character(unique(exon$seqnames)))
[1] "1" "2" "3" "4" "5" "6"
> head(names(temp_sequences))
[1] "1" "2" "3" "4" "5" "6"

> 

I guess I am good to go in that regard . :)

Anyhow, I tried to run the line with or without the _refseq_sep_ option, still getting the same error:

` NI810_codon_usage_ <- codon_usage_psite(filtered_list, annotation_dt, sample = "NI810_deduplicated.tr", fastapath = "fasta/genome_clean_v97.fa", fasta_genome = TRUE, gtfpath="/gtf/Homo_sapiens.GRCh38.97.gtf")`

or 

` NI810_codon_usage_ <- codon_usage_psite(filtered_list, annotation_dt, sample = "NI810_deduplicated.tr", fastapath = "fasta/genome_clean_v97.fa", fasta_genome = TRUE, gtfpath="/gtf/Homo_sapiens.GRCh38.97.gtf", refseq_sep=" ")`

> Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error: subscript contains invalid names

> 

Seems a bit strange right?

Thank you in advance!

Kind Regards,
Alex

**Comment by AlexFryd** [comment]
Hello Fabio,

Quick update!!!!

I re-rerun everything with the .fa used for the indexing: meaning before formating the header:

Thats what I got for the chuck of lines:

> > head(as.character(unique(exon$seqnames)))
[1] "1" "2" "3" "4" "5" "6"
> head(names(temp_sequences))
[1] "1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF"
[2] "10 dna:chromosome chromosome:GRCh38:10:1:133797422:1 REF"
[3] "11 dna:chromosome chromosome:GRCh38:11:1:135086622:1 REF"
[4] "12 dna:chromosome chromosome:GRCh38:12:1:133275309:1 REF"
[5] "13 dna:chromosome chromosome:GRCh38:13:1:114364328:1 REF"
[6] "14 dna:chromosome chromosome:GRCh38:14:1:107043718:1 REF"

> 

Rerun the _codon_usage_ with this fasta, using _refseq_sep_= " "

It worked!

I honestly do not know what was the problem still! But maybe you realized?

Thanks again for helping me!

Kind Regards,
Alex

**Comment by fabiolauria** [comment]
Hi Alex,
good to know everything is fine now. 
Actually, since the formatting of the header in the FASTA has previously made the chromosome IDs match, I cannot figure out why everything works using the original file + _refseq_sep_ (that in principle performs the same task). I guess something went wrong somewhere in executing the script.

I'll update you if something come to my mind. Meanwhile I'll close this issue.

Bests,
Fabio

PS: thank you for having scrolled through other issues before opening this one, even if it wasn't of much help. I appreciate that.
