### ISSUE TITLE
psite_info error

### ISSUE THREAD

**Issue by sanyuanqian** [LabTranslationalArchitectomics/riboWaltz#28]
Now I'm using psite_info functions to attach to each data table psite reporting, but I'm puzzled that how to set parameters if I want to attach both Psite, Asite and Esite nucleotides sequence information to the primary reads_list? I tried as :
reads_psite_list <- psite_info(filtered_list, psite_offset,site =c("psite","asite","esite"),
                               fastapath = "~/dmel-all-transcript-r6.04.fasta",
                               fasta_genome = FALSE,refseq_sep = " ") 
but the error is :
processing wt_ctrl_head_ribo_rep1.toTrans
1. adding p-site position
2. adding transcript region
3. adding nucleotide sequence(s)
Error: subscript contains invalid names

**Comment by sanyuanqian** [comment]
Eventually I have made the issue a bit clear after I learned from #24 and #16. Whatever for psite_info or codon_usage_psite functions, the error root is same : the transcript ID are not totally matched to the ID in the provided transcript.fasta or genome.fasta/annotation.gtf. To avoid this problem , be sure that:
1) the fasta you provided should be same to the one used in the alignment steps. Use transcript.fasta if you aligned reads to transcripts and use genome.fasta if you aligned reads to genome(even though some aligner could output MaptoTranscriptome.bam, ie STAR);
2) correctly specify the separator by refseq_sep regardless of genome.fa or transcript.fa provided (I had been trapped in it, when I use genome.fa the separator was not specified);
3) if transcript.fa used, specify fasta_genome = FALSE ;
     if genome.fa used, specify fasta_genome = TRUE and the path of annotation.gtf. Make sure the gtf file is same to the one used in indexing and mapping!

**Comment by fabiolauria** [comment]
Hi,
sorry for the delay. Are you still in trouble with the psite or codon_usage_psite functions?
I don't get if you already checked the transcript or gene names (since you used fasta_genome = FALSE, you aligned on transcriptome, I guess?) of all files to be sure everything is based on the same annotation. Did you?

**Comment by sanyuanqian** [comment]
Hi

Thanks for your reply!

Yeah, I think I have figured out it. It may be because of  the omission of "refseq_seq" parameter. I have posted my updated comment on github.


Thank you very much again!

> Hi,
> sorry for the delay. Are you still in trouble with the psite or codon_usage_psite functions?
> I don't get if you already checked the transcript or gene names (since you used fasta_genome = FALSE, you aligned on transcriptome, I guess?) of all files to be sure everything is based on the same annotation. Did you?

**Comment by fabiolauria** [comment]
Oh, okay. I saw your update, but didn't understand everything was fine. Then I think I can close this issue now.

If you need more help please don't hesitate to contact me or open a new issue.

Bests
Fabio
