### ISSUE TITLE
Vectorized input to `element_text()` is not officially supported. Codon_usage

### ISSUE THREAD

**Issue by AlexFryd** [LabTranslationalArchitectomics/riboWaltz#35]
Hello,

I am experiencing an issue when I try to use the codon_usage_psite function.

I have been using this command:
`NI810_codon_usage <- codon_usage_psite(filtered_list, annotation_dt, sample = "NI810_deduplicated.tr", fastapath = "fasta/genome.fa", fasta_genome = TRUE, gtfpath="/path/to/gtf/Homo_sapiens.GRCh38.97.gtf", refseq_sep=" ")`

Which has been working until last time I had used the program (it has been sometime, however).

However, now I am getting this:

> Vectorized input to `element_text()` is not officially supported.
Results may be unexpected or may change in future versions of ggplot2.

Trying to plot using:
 `NI810_codon_usage[["plot"]]` results in corrupted pdf, which cannot be recovered.

I had opened another issue in the past (#24), which have been resolved now, of course, just maybe to offer extra help about my current setting in the command.

Do you maybe know what the problem is?

Thanks in advance!

Kind Regards,
Alexandros

**Comment by fabiolauria** [comment]
Hi Alexandros.
I have just tested the function by replicating the command line you reported above but using my own data, FASTA and GTF, i.e.:

`test <- codon_usage_psite(psite_list, anno_dt, sample = "wt1", fastapath = "GRCm38.p6.genome.fa", fasta_genome = TRUE, gtfpath="gencode.vM22.primary_assembly.annotation.gtf", refseq_sep=" ")`

The resulting object _test_ is fine: as expected, it includes both the barplot and the data.table with its data.

I am wondering: are you sure the FASTA and the GTF come from the same annotation and repository? Did you check that the name of the sequences in the FASTA (after splitting them by using `refseq_sep=" "`) correspond to the names in the GTF? Are you using the last version of riboWaltz (Jenuary 2021)?

Best,
Fabio

**Comment by fabiolauria** [comment]
Hi Alexandros,
Hopefully you have cleared your doubts, so I'm closing this issue for now.
If you need some more help please don't hesitate to reopen it and contact me again.

Best
Fabio
