### ISSUE TITLE
Multiple samples error in rlength_distr

### ISSUE THREAD

**Issue by agoldkamp** [LabTranslationalArchitectomics/riboWaltz#41]
Hello,

I am able to generate read length distribution plots for individual samples. However, when I try to use multiple samples I get this error:

example_length_dist_rep <- rlength_distr(reads_list,
                             sample = list("Liver_avg" = c("Liver_2.norrna_notrna_ref_mRNA", "Liver_3.norrna_notrna_ref_mRNA")),
                             cl = 99, multisamples = "average",
                             colour = "gray70")

Error in rlength_distr(reads_list, sample = list(Liver_avg = c("Liver_1.norrna_notrna_ref_mRNA",  : 
  unused arguments (multisamples = "average", colour = "gray70")

Any ideas on how to resolve this issue?

Thank you

**Comment by fabiolauria** [comment]
Hi there.

_rlength_distr_ works fine with my own data and the very same options from your chunk. Are you sure you have the latest version of riboWaltz? A couple of things changed in the last updates, especially regarding the handling of multiple samples in _rlength_distr_. E.g., previously the parameter multisamples was differently defined.

Best
Fabio

**Comment by agoldkamp** [comment]
I had the latest version but redownloaded it and that did the trick!

Thank you for your help!
