### ISSUE TITLE
codon_usage_psite problem

### ISSUE THREAD

**Issue by z626093820** [LabTranslationalArchitectomics/riboWaltz#48]
when i use the command:
> example_cu_scatter_2samples <- codon_usage_psite(comparison_list, annotation_dt, sample = c("All", "Only_28"),fastapath = "E:/riboseq/NSP306_trifida_chr_v3.fa",fasta_genome = TRUE,gtfpath='E:/riboseq/NSP306_trifida_chr_v3.gtf',frequency_normalization = FALSE)

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error in `:=`(p_site_codon, as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)],  : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

how can i slove the problem
thanks

**Comment by fabiolauria** [comment]
It seems some of the object you passed is not a data.table or doesn't exist.
Is annotation_dt a data table? I guess so.
Do comparison_list[["All"]] and comparison_list[["Only_28"]] exist and are both of them data tables? Maybe not.

**Comment by z626093820** [comment]
i see the 'comparison_list',and change the command:

> example_cu_scatter_2samples <- codon_usage_psite(comparison_list, annotation_dt, sample = c("whole_sample", "subsample_28nt"),fastapath = "E:/riboseq/NSP306_trifida_chr_v3.fa",fasta_genome = TRUE,gtfpath='E:/riboseq/NSP306_trifida_chr_v3.gtf',frequency_normalization = FALSE)


then the running is ok, thank you!
