### ISSUE TITLE
there is no figure using command "rlength_distr"

### ISSUE THREAD

**Issue by z626093820** [LabTranslationalArchitectomics/riboWaltz#49]
![image](https://user-images.githubusercontent.com/37371455/141881265-5c1bf57e-3207-46b6-b1d3-c01c16c1ac84.png)
![image](https://user-images.githubusercontent.com/37371455/141881419-3bb42a9d-f977-4480-b407-440f36fa156e.png)

when i use command :
"> example_length_dist_split <-  rlength_distr(comparison_list,sample = c("whole_sample", "start_codon"),plot_style = "split",colour = c("dodgerblue", "gray70"))
> example_length_dist_split[["plot"]]
NULL"

there is no figure!
how can is slove the problem, thank you!

**Comment by fabiolauria** [comment]
You can clearly see that `example_length_dist_split` doesn't include any element called _plot_. You have _dt_, _plot_whole_sample_ and _start_codon_ and that's it. So you have two separated plots and not a single plot with both of them. For that you should _define a **named list** containing the character strings specifying **the name of the sample(s) of interest**_ (from documentation):

```
 sample_list <- list("Only_start" = c("start_codon"),
 		     "All" = c("whole_sample"))
```

Then

```
 example_length_dist_split <-  rlength_distr(comparison_list,
 					     sample = sample_list,
 					     plot_style = "split",
 					     colour = c("dodgerblue", "gray70"))
 example_length_dist_split[["plot"]]
```

**Comment by z626093820** [comment]
![image](https://user-images.githubusercontent.com/37371455/141945802-e0b8590b-8eb6-4018-bff0-08fd9e0efacf.png)
when i use the changed command, there is no figure out.
that's why
thank you!

**Comment by fabiolauria** [comment]
Ummm and if you try to add `multisamples = "average"`?

**Comment by z626093820** [comment]
yes,there is a figure out! thank you!

**Comment by fabiolauria** [comment]
Okay, there are too many combinations and I messed up somewhere. I'll fix it and be more explicit in the ReadMe.
Thank you for opening this issue.
