### ISSUE TITLE
Bug in rlength_distr()

### ISSUE THREAD

**Issue by bontus** [LabTranslationalArchitectomics/riboWaltz#5]
Hi Fabio,

One of my datasets has been generated with rather long reads that had to be trimmed to <= 35nt length, however, their length distribution is not normally distributed and not centered around ~30, causing rlength_distr() to throw the following error:

> Error in seq.default(xmin + ((xmin)%%2), xmax, by = floor((xmax - xmin)/7)) : 
>   invalid '(to - from)/by'

I tracked down its origin and this behavior can be fixed by changing line 42 in read_length_plot.R to prevent a step size of 0:

original
`scale_x_continuous(limits = c(xmin - 0.5, xmax + 0.5), breaks = seq(xmin + ((xmin) %% 2), xmax, by = floor((xmax-xmin)/7)))`
fix
`scale_x_continuous(limits = c(xmin - 0.5, xmax + 0.5), breaks = seq(xmin + ((xmin) %% 2), xmax, by = max(c(1,floor((xmax - xmin)/7)))))`

Best,
René

**Comment by fabiolauria** [comment]
Hi Renè,
thanks for the tip, I'll fix it in a while.

Bests,
Fabio
