### ISSUE TITLE
bamtoist problem

### ISSUE THREAD

**Issue by z626093820** [LabTranslationalArchitectomics/riboWaltz#50]
![image](https://user-images.githubusercontent.com/37371455/142163815-8b226732-0394-444a-9fe5-92ca6301068e.png)
![image](https://user-images.githubusercontent.com/37371455/142163957-bcfc9eb4-84f1-4f6d-ad3c-66ab5c0f2f6e.png)

why there is a error? but i can get a result
thank you!

**Comment by fabiolauria** [comment]
Hi.
By searching around I found:

> The x$.self$finalize() function is called just before the object is removed. At this stage all the data has already returned and your result object was generated

But also

> It seems to be some R-internal thing and is happening random.

> It is problem that may occur when using Rcpp modules. It is reported in a few other places, but not solution have been found.

So, nothing really connected to riboWaltz, it seems.
