### ISSUE TITLE
how can i change colour and add the data tags above of the bar 

### ISSUE THREAD

**Issue by z626093820** [LabTranslationalArchitectomics/riboWaltz#51]
![image](https://user-images.githubusercontent.com/37371455/142168775-a4f5cedb-2bd7-40a3-92b2-9033226ae4d5.png)

when i use the command :
example_length_dist_zoom <- rlength_distr(reads_list, sample = "Samp1", cl = 99)
example_length_dist_zoom[["plot_Samp1"]]

how can i change colour and add the Data labels above of the bar ,what parameters can i use?
thank you!

**Comment by fabiolauria** [comment]
For changing the colour, use the parameter `colour`. It's as simple as it might be. Please, read the supporting documentation associated to the functions or the manual (keep in mind the ReadMe only summarize what you can do) before opening new issues. Just as an example, `?rlength_distr` reports:

> colour: Character string or character string vector specifying the colour of the bar plot(s).

It's not possible to add data labels. Again, if it's not written in the documentation, it's not an available option. This is why riboWaltz provides the data table with the data for generating the plot, so you can use your own script and change the default visualization.
