### ISSUE TITLE
the problem of the p site of 30nt reads

### ISSUE THREAD

**Issue by z626093820** [LabTranslationalArchitectomics/riboWaltz#52]
![image](https://user-images.githubusercontent.com/37371455/142203954-9a7dff84-f460-4d83-9365-8289fd946e6a.png)
Excuse me again, i can plot the 28nt periodicity， but there is a error in 30 nt reads

how can i slove the problem?
thank you!

**Comment by fabiolauria** [comment]
Could you please try use `plot_title = "sample"` instead of `plot_title = "sample.length_range"` and see what happen?
And also run:

```
length_range <- 30
length_sample <- reads_psite_list[["total_trans"]]$length
lmin_temp <- quantile(length_sample, 0.05)
lmax_temp <- quantile(length_sample, 0.95)
length_sample <- unique(length_sample[length_sample %between% c(lmin_temp, lmax_temp)])
length_range_pl <- sort(intersect(length_sample, length_range))
minlr <- min(length_range_pl)
maxlr <- max(length_range_pl)
minlr
maxlr 
```

and report the result?

**Comment by z626093820** [comment]
when i use use plot_title = "sample" instead of plot_title = "sample.length_range",there is no error!,i can get a figure.

but when i use the command:
length_range <- 30
length_sample <- reads_psite_list[["total_trans"]]$length
lmin_temp <- quantile(length_sample, 0.05)
lmax_temp <- quantile(length_sample, 0.95)
length_sample <- unique(length_sample[length_sample %between% c(lmin_temp, lmax_temp)])
length_range_pl <- sort(intersect(length_sample, length_range))
minlr <- min(length_range_pl)
maxlr <- max(length_range_pl)
minlr
maxlr

there is a error
![image](https://user-images.githubusercontent.com/37371455/142366366-62c099b2-4d47-4766-b53c-e68d3f8b3bb9.png)

**Comment by fabiolauria** [comment]
Okay, so it's something related to the title of the plot and specifically to the addition of the length of the reads used.
Sorry for the error about %between%, I forgot to tell you to load the data.table package before that. Could you do please load it and rerun the lines? In the meanwhile I'll try the function with a dataset of mine.

**Comment by z626093820** [comment]
when i load the data.table package, there is no error.
thank you!

![image](https://user-images.githubusercontent.com/37371455/142372830-57f6aef8-3202-404c-9027-a5ec6cea0a7c.png)

**Comment by fabiolauria** [comment]
Those errors are similar to the ones you reported at the beginning. Just to get deeper, could you run all the lines reporting the output of each of them as in the following script?

```
library(data.table)
length_range <- 30
length_sample <- reads_psite_list[["total_trans"]]$length
head(length_sample)
lmin_temp <- quantile(length_sample, 0.05)
lmin_temp 
lmax_temp <- quantile(length_sample, 0.95)
lmax_temp 
length_sample <- unique(length_sample[length_sample %between% c(lmin_temp, lmax_temp)])
length_sample 
length_range_pl <- sort(intersect(length_sample, length_range))
length_range_pl 
minlr <- min(length_range_pl)
minlr
maxlr <- max(length_range_pl)
maxlr 
```

Thank you.

**Comment by z626093820** [comment]
there is a out:
![image](https://user-images.githubusercontent.com/37371455/142375154-740afed4-feec-46a9-9d28-87d7e250cf1c.png)

**Comment by z626093820** [comment]
i have another question :
when i use software 'star' to alignment, i can get the bam file compared to the genome(01Aligned.sortedByCoord.out.bam) and the bam file compared to the transcript(01Aligned.toTranscriptome.out.bam), Which one should I choose for analysis?
thank you!

**Comment by fabiolauria** [comment]
Only BAM files with mapping information based on **transcriptome coordinates** are allowed. riboWaltz can't handle genome coordinates. Meaning that with STAR you can either map directly on the transcriptome or map on the genome and asking for an additional BAM file based on **transcriptome coordinates**.

Thank you for the outcome of the length_reange-related lines, I now understand which is the problem and I'll fix it as soon as possible, uploading the new version of the function on GitHub.

Best
Fabio

**Comment by z626093820** [comment]
thank you for your ansower!
best wishes!

**Comment by z626093820** [comment]
thank you for your answer!
best wishes!
