### ISSUE TITLE
Error in h(simpleError(msg, call)) :    在为'subseq'函数选择方法时评估'x'参数出了错: subscript contains invalid names

### ISSUE THREAD

**Issue by z626093820** [LabTranslationalArchitectomics/riboWaltz#53]
hello！when is use the command：
> example_cu_barplot <- codon_usage_psite(reads_psite_list, annotation_dt, sample = "total_trans",fastapath = "E:/riboseq/rice/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa",fasta_genome = TRUE,gtfpath='E:/riboseq/rice/Oryza_sativa.IRGSP-1.0.52-update.gtf',frequency_normalization = FALSE)
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error in h(simpleError(msg, call)) : 
  在为'subseq'函数选择方法时评估'x'参数出了错: subscript contains invalid names 

how can i slove this problem？
thanks

**Comment by fabiolauria** [comment]
Hi,
that is usually an error related to inconsistent transcript names in reads_psite_list wrt the ones reported in the GTF and/or the the FASTA. You should try and check their consistency. Also refer to [issue 16](https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/16) and [issue 24](https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/24) that are somehow related and might help you to understand what is going on, even if they are a bit old.

Let me know.

Best
Fabio

**Comment by z626093820** [comment]
I run the command 
![image](https://user-images.githubusercontent.com/37371455/148037257-80c7b488-d176-4eb2-ac4a-9559c2f02810.png)
there is problems about the name, how can to do to slove the problems?
thank you very much!

**Comment by fabiolauria** [comment]
Is name_tr the a vector containing the name of the transcripts from reads_psite_list? If so, it makes sense that none them can be found in name_seq: according to your first post, you aligned on chromosome sequences (because of fasta_genome = TRUE) so I guess name_seq is something like "chr1, chr2, etc".

You should run:

```
library(data.table)

gtfpath = "E:/riboseq/rice/Oryza_sativa.IRGSP-1.0.52-update.gtf"
txdbanno <- GenomicFeatures::makeTxDbFromGFF(file = gtfpath, format = "gtf")
exon <- suppressWarnings(GenomicFeatures::exonsBy(txdbanno, by = "tx", use.names = TRUE))
exon <- as.data.table(exon[unique(names(exon))])

fastapath = "E:/riboseq/rice/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa"
sequences <- Biostrings::readDNAStringSet(fastapath, format = "fasta", use.names = TRUE)
```

Then you can compare exon$seqnames and names(sequences) - that should include the same strings of chromosome names - and you can compare exon$group_name and reads_psite_list$transcript - which again should include matching strings of transcript names.

**Comment by z626093820** [comment]
sorry,i am poor of R, I run the command follows:
![image](https://user-images.githubusercontent.com/37371455/148047787-f30930c3-fd34-4e9b-81fe-ef1cfa26941d.png)
![image](https://user-images.githubusercontent.com/37371455/148047823-038251cd-e57f-4da6-bdf3-793ff8b21173.png)
![image](https://user-images.githubusercontent.com/37371455/148047845-efe3c046-3f09-41cc-863a-d56fa7c8b334.png)
![image](https://user-images.githubusercontent.com/37371455/148047900-53768be2-fa22-4063-a4bf-5b42912a0721.png)
**why there is null at last ,but i can find the transcript at the reads_psite_list:**
![image](https://user-images.githubusercontent.com/37371455/148047999-0eeb8776-c7b1-4369-84d8-d10a51aad925.png)

**Comment by fabiolauria** [comment]
Yeah, sorry for the last line of code. I didn't take into consideration that reads_psite_list is actually a list.
BTW, it seems transcript names in reads_psite_list  and in exon$group_name match. On the other hand, chromosomes in the GTF are labeld as "1", "2", "3" etc, while the FASTA sequences are named "1 ...info...", "2 ...info..." (same name as in the GTF, then a space, then additional info).
So there is not a match. Given this, I think you should add refseq_sep = " " (space character) to your run of _codon_usage_psite_. From the documentation, refseq_sep "specifies the separator between reference sequences' name and additional information to discard, stored in the headers of the FASTA file specified by _fastapath_ (if any). [...] All characters before the first occurrence of the specified separator are kept".

**Comment by z626093820** [comment]
sorry for reply late, i add the command 'refseq_sep = ", then the problems is solved.
but when i run the next command :
> example_cu_scatter_2samples <- codon_usage_psite(comparison_list, annotation_dt, sample = c("whole_sample", "subsample_28nt"),fastapath = "E:/ricetotalreads/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa",fasta_genome = TRUE,gtfpath='E:/ricetotalreads/Oryza_sativa.IRGSP-1.0.52-update.gtf',frequency_normalization = FALSE,refseq_sep = " ")
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error in `:=`(p_site_codon, as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)],  : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
I search it on the www.baidu.com ,i can't slove. how can i slove the problem?
thank you!

**Comment by fabiolauria** [comment]
It looks like either comparison_list[["whole_sample"]] or comparison_list[["subsample_28nt"]] or both of them are not data tables or do not exist, so the syntax used and the function _:=_ are not campatible with the structure.

**Comment by z626093820** [comment]
yes,I forgot to replace the sample name with reads length. I have no question.Thank you for your help!

**Comment by fabiolauria** [comment]
You are welcome.

**Comment by q02y** [comment]
library(glmnet)
> set.seed(1234)
> SAheart_clean[,10]<-as.numeric(as.character(SAheart_clean[,10]))
> index<-sample(x=1:nrow(SAheart_clean),size = 0.7*nrow(SAheart_clean))
> train<-SAheart_clean[index,]
> test<-SAheart_clean[-index,]
> #lasso模型
> train<-as.matrix(train)
> fit_lasso<-glmnet(x=as.matrix(train[,-10]),
+                   y=train[,10],
+                   family = 'binomial',alpha = 1)
Warning message:
In storage.mode(xd) <- "double" : NAs introduced by coercion
> plot(fit_lasso,xvar='lambda')
> #交叉验证法确定λ
> fit_lasso_cv<-cv.glmnet(x=as.matrix(train[,-10]),
+                         y=train[,10],
+                         alpha=1)
Error in h(simpleError(msg, call)) : 
  在为'as.matrix'函数选择方法时评估'x'参数出了错: invalid class 'NA' to dup_mMatrix_as_dgeMatrix 
In addition: There were 11 warnings (use warnings() to see them)

这个报错怎么修改？、可以给一些帮助吗？

**Comment by fabiolauria** [comment]
Is this a message somehow related to riboWaltz?
