### ISSUE TITLE
how to get the number of read extremities from psite plot

### ISSUE THREAD

**Issue by cornecu** [LabTranslationalArchitectomics/riboWaltz#57]
Thank you so much for creating this powerful tools and I am able to run all commands successfully for my riboseq data. 

However, when I try to export the number of reads from psite plot, I don't get what I need from best_offset.txt file. Is there anyway I can get the actual number reads from the psite plot?

Thank you so much in advance!

See the figure I pulled out from your website and I add red arrows just from examples (didn't add all arrows in this figure and I just show my purpose). I want to get the actual read number for this plot so I can plot it by myself like in the excel or use this data for other usages.

![meta_psite_length28](https://user-images.githubusercontent.com/72764945/164317789-69d77789-8428-44fd-b8e2-d5946cc4184b.png)

**Comment by fabiolauria** [comment]
Hi.
I'm happy to hear everything works properly.
riboWaltz doesn't return the numbers for generating the plot you reported. However you can easily retrieve them manually. It's just a matter of counting the extremity of all reads with a specified length mapping across annotated translation initiation sites.
Something like this, for a specified LENGTH, should work:

```
dt <- reads_list[["SAMPLE"]][, end5_from_start := end5 - cds_start
                              ][, end3_from_start := end3 - cds_start
                                ][(end5_from_start < 0 & end3_from_start >= 0) | (end5_from_start <= 0 & end3_from_start > 0)]


i_dt <- dt[length == LENGTH]

setkey(i_dt, end5_from_start)
end5_counts_dt <- i_dt[CJ((-LENGTH + 1):0), list(signal = .N), by = .EACHI
                    ][, end := "end5"]

setkey(i_dt, end3_from_start)
end3_counts_dt <- i_dt[CJ(0:(LENGTH - 1)), list(signal = .N), by = .EACHI
                    ][, end := "end3"]
```

Where **reads_list** is the list of data samples before computing the P-site and SAMPLE specify the name of one data table. You can also use **psite_list** and the code still works. Then you can bind __end5_counts_dt__ and __end3_counts_dt__ by adding a column to keep trace of the extremities and plot the profile.

Let me know if I answered your question.

Best
Fabio

**Comment by cornecu** [comment]
Hi Fabio,

Thank you so much for your quick response. I am sorry to get back to you late. This is definitely helpful.
