### ISSUE TITLE
Question about  rends_heat (Error in `[.data.frame`(annotation, l_utr5 >= utr5l & l_cds > 2 * (cdsl +  :    object 'transcript' not found)

### ISSUE THREAD

**Issue by cornecu** [LabTranslationalArchitectomics/riboWaltz#58]
Hi Lauria Fabio,

Thank you so much for creating ribowaltz tools. When I ran my bam files with rends_heat, I keep meeting the same error and had no way to go through. Could you provide any insight about my problems?
 

I used the example in your manual, and everything worked. I suspect my bam files have problems but importing from bamtolist has no problem. I also tried different size of bam files and met the same error. I also double-checked my readlist format (list of list datatable) to match format with your example readlist (like transcript, end5, end3, length, cds_start, cds_stop ) but still meet this error. I attached my bam file and annotation here.

Do you any insight about this error? I will send the small bam files to your gmail and annotation.

Thank you so much.

Here is my code:

library("riboWaltz")
library("data.table")
setwd("~/Documents/Riboseq/sequencing_submit/2020_8_31/rpf_size_DESeq2/riboWaltz")

#### 
annotation_dt<-read.table("all.transcripts.info.riboWaltz.annotation.txt", header = TRUE, sep="\t")
name_of_bams <- c("Control")
names(name_of_bams) <- c("N3")
reads_list <- bamtolist(bamfolder = "~/Documents/Riboseq/sequencing_submit/2020_8_31/rpf_size_DESeq2/riboWaltz", name_samples = name_of_bams, annotation = annotation_dt)

## 
My_ends_heatmap <- rends_heat(reads_list, annotation_dt, sample = "Control", cl = 80, utr5l = 25, cdsl = 50, utr3l = 25)
My_ends_heatmap[["plot"]]

**Comment by fabiolauria** [comment]
Hi Hailong Yang,
I tested your code and I found out the issue is caused by _annotation_dt_ . Problem is, _annotation_dt_ is not a data table, as it should be. You can easily solve this by reading the txt using

`fread("all.transcripts.info.riboWaltz.annotation.txt", header = TRUE, sep="\t") `

where _fread_ belongs to the data.table package.

Let me know if this trick solve your problem.

Best
Fabio

**Comment by cornecu** [comment]
> fread("all.transcripts.info.riboWaltz.annotation.txt", header = TRUE, sep="\t")

Hi Fabio,

It indeed is my annotation problems. Thank you so much for clarification. It works very well

Best,
Cornecu
