### ISSUE TITLE
bedtolist Error: paste(bamfolder, n, sep = "/") : object 'bamfolder' not found

### ISSUE THREAD

**Issue by scottiadamson** [LabTranslationalArchitectomics/riboWaltz#6]
When I give bedtolist the command:

`reads_list <- bedtolist(bedfolder=paste(base_dir,sample, '/', sep = ''), annotation=annotation)`

I get the error:

> reading B6J_28months_1_transcripts.bed
Error in paste(bamfolder, n, sep = "/") : object 'bamfolder' not found

I solve it if I define the bamfolder globally the same as the bedfolder, but I think line 273 of combine_bam.R should be 
`filename <- paste(bedfolder, n, sep = "/")`
instead of 
`filename <- paste(bamfolder, n, sep = "/")`

**Comment by fabiolauria** [comment]
Hi,
thank you for your feedback. The bug has been fixed.

Bests
Fabio
