### ISSUE TITLE
ribowaltz for R version 4.1.2

### ISSUE THREAD

**Issue by dksenthil** [LabTranslationalArchitectomics/riboWaltz#60]
getting this error.
```

> BiocManager::install("riboWaltz",force = T)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.14 (BiocManager 1.30.18), R 4.1.2 (2021-11-01)
Installing package(s) 'riboWaltz'
Warning message:
package ‘riboWaltz’ is not available for Bioconductor version '3.14'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

**Comment by fabiolauria** [comment]
Hi, it is clear **riboWaltz** is here treated as a Bioconductor package, which is not.
Where did you find `BiocManager::install("riboWaltz",force = T)` reported as the proper command for getting riboWaltz installed? It is true that _BiocManager::install_ should handle Github packages as well, but clearly this is not the right syntax. 
You better stick with the lines reported at the [installation](https://github.com/LabTranslationalArchitectomics/riboWaltz#installation) section of the readMe. Have you already tried that way? If so and you didn't manage to get **riboWaltz** installed, you R version is maybe too recent for it.

Either ways, please keep me updated.

Best
Fabio

**Comment by dksenthil** [comment]
Thanks. Solved.
