### ISSUE TITLE
error with codon_usage_psite()

### ISSUE THREAD

**Issue by beth60197** [LabTranslationalArchitectomics/riboWaltz#61]
Hi there, 

I used codon_usage_psite() and it worked ok with default settings, however, when I specified site ="asite" I got the following warning and no data in the output.

> more reference sequences (from FASTA or BSgenomes) than transcript IDS (from annotation data table)
> 257635 reference sequences discarded.

I reattempted again with default settings and it failed to work, returning same problem as above.

Any help would be great!

*edit : it works fine without frequency_normalisation = F. When True, it always returns the above error.

**Comment by fabiolauria** [comment]
Hi,
it seemed that by specifying _site ="asite"_ something went wrong with the IDs and names assigned to the transcripts.
This is pretty odd: the commands associated with the parameter _site_ are only used to extract three nucletotides of interests. No additional modifications to either the structure or the content of the data tables take place, so up to now I have no clue about what happened.
Are you 100% sure you didn't change anything after the first trial with _site ="psite"_ and the next ones? Did you used the very same dataset, annotation and parameters (in particular _frequency_normalisation_ , given your last comment)?

**Comment by fabiolauria** [comment]
I just tried with a dataset of mine, using both _frequency_normalisation = F_ and _frequency_normalisation = T_ and I got no errors whatsoever.
Nevertheless, I checked the code and the only chunk related to the "more reference sequences [...]" message is where transcript sequence names are comparted with the transcript names reported in the annotation table through something like this:

`setequal(names(transcript_sequences), as.character(annotation$transcript))`

where _transcript_sequences_ is a readDNAStringSet object obtained either from the specified  FASTA (if you aligned on the trasnscriptome) or from the FASTA+GTF file (if you aligned on the genome).
Without additional details I cannot be of more help, but I would hypothesize something possibly related to the _refseq_sep_ parameter is behind all of this.

**Comment by beth60197** [comment]
Hi there, 

No the only two parameters I had changed were site and frequency_normalisation. When frequency_normalisation is True I all the reference sequences are discarded. I include the transcriptome in fastapath

**Comment by fabiolauria** [comment]
Could you please show me the command you run that returned the error above?
Also, could you please try to run the following lines and report the outcome of all of them but the first one?

```
tr_sequences <- Biostrings::readDNAStringSet(PATH/TO/FASTAFILE.fasta, format = "fasta", use.names = TRUE)
head(names(tr_sequences))
head(ANNOTATION_DT$transcript)
setequal(names(tr_sequences), as.character(ANNOTATION_DT$transcript))
length(setdiff(names(tr_sequences), as.character(ANNOTATION_DT$transcript)))
length(setdiff(as.character(ANNOTATION_DT$transcript), names(tr_sequences)))

```
where

- PATH/TO/FASTAFILE.fasta is the path to FASTA file with transcriptome sequences, including the name of the file and its extension (the one you should have passed to parameter `fastapath `of _codon_usage_psite_)
- ANNOTATION_DT is the data table which reports transcript names + length of CDSs, UTRs and transcripts (the one you should have passed to parameter `annotation`of _codon_usage_psite_)

**Comment by beth60197** [comment]
Hi there,

I'm using the following code

`codon_usage_psite(reads_psite_list, annotation_dt, sample =c("sample1","sample2"), fastapath  = fasta , fasta_genome =T, frequency_normalization =T ,  gtfpath = gtf)`

Output is 

> head(names(tr_sequences))
ENST00000631435.1 cdna chromosome:GRCh38:CHR_HSCHR7_2_CTG6:142847306:142847317:1 gene:ENSG00000282253.1 gene_biotype:TR_D_gene transcript_biotype:TR_D_gene gene_symbol:TRBD1 description:T cell receptor beta diversity 1 [Source:HGNC Symbol;Acc:HGNC:12158]
ENST00000415118.1 cdna chromosome:GRCh38:14:22438547:22438554:1 gene:ENSG00000223997.1 gene_biotype:TR_D_gene transcript_biotype:TR_D_gene gene_symbol:TRDD1 description:T cell receptor delta diversity 1 [Source:HGNC Symbol;Acc:HGNC:12254]                     
ENST00000448914.1 cdna chromosome:GRCh38:14:22449113:22449125:1 gene:ENSG00000228985.1 gene_biotype:TR_D_gene transcript_biotype:TR_D_gene gene_symbol:TRDD3 description:T cell receptor delta diversity 3 [Source:HGNC Symbol;Acc:HGNC:12256]                       
ENST00000434970.2 cdna chromosome:GRCh38:14:22439007:22439015:1 gene:ENSG00000237235.2 gene_biotype:TR_D_gene transcript_biotype:TR_D_gene gene_symbol:TRDD2 description:T cell receptor delta diversity 2 [Source:HGNC Symbol;Acc:HGNC:12255]                       
ENST00000632684.1 cdna chromosome:GRCh38:7:142786213:142786224:1 gene:ENSG00000282431.1 gene_biotype:TR_D_gene transcript_biotype:TR_D_gene gene_symbol:TRBD1 description:T cell receptor beta diversity 1 [Source:HGNC Symbol;Acc:HGNC:12158]                       
ENST00000633010.1 cdna chromosome:GRCh38:CHR_HSCHR14_3_CTG1:105895279:105895294:-1 gene:ENSG00000282274.1 gene_biotype:IG_D_gene transcript_biotype:IG_D_gene gene_symbol:IGHD4-17 description:immunoglobulin heavy diversity 4-17 [Source:HGNC Symbol;Acc:HGNC:5503]
>   head(annotation_dt$transcript)
[1] "ENST00000000233" "ENST00000000412" "ENST00000000442" "ENST00000001008" "ENST00000001146" "ENST00000002125"
>   setequal(names(tr_sequences), as.character(annotation_dt$transcript))
[1] FALSE
>   length(setdiff(names(tr_sequences), as.character(annotation_dt$transcript)))
[1] 257635
>   length(setdiff(as.character(annotation_dt$transcript), names(tr_sequences)))
[1] 235844

**Comment by fabiolauria** [comment]
Hi,
thank you for the trials. There are a couple of things that can be related to your issue.
First of all, since you mapped your reads directly on the transcriptome, _fasta_genome_ should be set to **FALSE**. From the documentation:

> fasta_genome: [...] FALSE implies nucleotide sequences of transcripts are provided.

By setting  _fasta_genome = FALSE_, then _gtfpath_ won't be considered because:

> gtfpath is required if and only if nucleotide sequences of a genome assembly are provided.

Second, as previously hypothesized, _refseq_sep = "."_ might be the key to got matches between _names(tr_sequences)_ and _as.character(annotation_dt$transcript)_: the name of the sequences in the FASTA are of the type ENST00000631435.1 while the name of the transcripts in the annotation data table are like ENST00000631435, without the dot and the version. So you need to truncate the header of the fasta at the "." (dot) character:

> refseq_sep Character specifying the separator between reference sequences' name and additional information to discard, stored in the headers of the FASTA file specified by fastapath (if any). It might be required for matching the reference sequences' identifiers reported in the input list of data tables. All characters before the first occurrence of the specified separator are kept.

So I would try with something like this:

`codon_usage_psite(reads_psite_list, annotation_dt, sample =c("sample1","sample2"), fastapath = fasta , fasta_genome = F, frequency_normalization = T , refseq_sep = ".")`

Let me know.
Fabio
