### ISSUE TITLE
Would it be possible to find the P-site of novel intergenic genes?

### ISSUE THREAD

**Issue by Dongxu-Zheng** [LabTranslationalArchitectomics/riboWaltz#62]
Hi, thanks for developing such great software for Ribo-seq analysis!

I have some long-read RNA sequencing data and I have identified some coding novel intergenic genes. But as they are novel intergenic genes, they are not well annotated. I was wondering if I can find the P-sites of these intergenic genes via riboWaltz? I try to run the pipeline. It seems that the P-sites were determined by the annotation_df and  Bam files. So I guess If the intergenic genes are not included in the annotation_df (because they are not well annotated), I can't obtain the P-sites of these intergenic genes. Many thanks for any suggestions!

Cheers,
Dongxu Zheng

**Comment by fabiolauria** [comment]
Dear Dongxu Zheng,
thank you for thinking about riboWaltz for your project.
Unfortunately, as you mentioned, riboWaltz is not suitable for identifying P-sites of reads mapping in novel intergenic genes. The only think I can think of is 1) to use riboWaltz to find the P-site offset according to the reads mapping on annotated _transcripts_  (keep in mind riboWaltz works with transcript-based annotation_df) and 2) manually inspect the presence of the three nucleotide periodicity (or other P-site-related features) on the intergenic genes of interests. It would require a bit of work from your side for step #2, though.

Let me know if I can be of more help.

Best
Fabio

**Comment by Dongxu-Zheng** [comment]
> Dear Dongxu Zheng, thank you for thinking about riboWaltz for your project. Unfortunately, as you mentioned, riboWaltz is not suitable for identifying P-sites of reads mapping in novel intergenic genes. The only think I can think of is 1) to use riboWaltz to find the P-site offset according to the reads mapping on annotated _transcripts_ (keep in mind riboWaltz works with transcript-based annotation_df) and 2) manually inspect the presence of the three nucleotide periodicity (or other P-site-related features) on the intergenic genes of interests. It would require a bit of work from your side for step 2, though.
> 
> Let me know if I can be of more help.
> 
> Best Fabio

Hi Fabio,

Thanks for your quick reply! I read this paper: [Long RNA Sequencing and Ribosome Profiling of Inflamed β-Cells Reveal an Extensive Translatome Landscape](https://diabetesjournals.org/diabetes/article-abstract/70/10/2299/137919/Long-RNA-Sequencing-and-Ribosome-Profiling-of?redirectedFrom=fulltext), in which the RPFs were aligned to the novel transcriptome created by Long-RNA seq data and some TIS were identified in the novel transcripts. I was confused about how to combine the Ribo-seq and long-read RNA-seq. I guess these novel transcripts in this paper are not intergenic, right? Thank you!

Best,
Dongxu

**Comment by fabiolauria** [comment]
Hi Dongxu,
I have no access to the paper, but I think it doesn't really matter the position of the novel transcripts. To be more precise, I guess that once the novel transcriptome was defined (likely based on the mapping long reads and splicing analysis), RiboSeq reads were just aligned on it. Then, accumulation of signal corresponding to putative TIS would be detectable.
Whatever the procedure, tools such as riboWaltz mainly based on already annotated transcripts are not really an option for this kind of analysis. I would say that either softwares more open to hidden and unknown ORF should be taken into consideration or manual digging of the data is required.

Best
Fabio

**Comment by Dongxu-Zheng** [comment]
> Hi Dongxu, I have no access to the paper, but I think it doesn't really matter the position of the novel transcripts. To be more precise, I guess that once the novel transcriptome was defined (likely based on the mapping long reads and splicing analysis), RiboSeq reads were just aligned on it. Then, accumulation of signal corresponding to putative TIS would be detectable. Whatever the procedure, tools such as riboWaltz mainly based on already annotated transcripts are not really an option for this kind of analysis. I would say that either softwares more open to hidden and unknown ORF should be taken into consideration or manual digging of the data is required.
> 
> Best Fabio

Thanks for your kind help and quick reply. I will find other options for this analysis. And I think I can close this issue :)

Cheers,
Dongxu

**Comment by Dongxu-Zheng** [comment]
> Hi Dongxu, I have no access to the paper, but I think it doesn't really matter the position of the novel transcripts. To be more precise, I guess that once the novel transcriptome was defined (likely based on the mapping long reads and splicing analysis), RiboSeq reads were just aligned on it. Then, accumulation of signal corresponding to putative TIS would be detectable. Whatever the procedure, tools such as riboWaltz mainly based on already annotated transcripts are not really an option for this kind of analysis. I would say that either softwares more open to hidden and unknown ORF should be taken into consideration or manual digging of the data is required.
> 
> Best Fabio

Hi Fabio,

I have to come back to you again :)

I have generated a full annotation file of all my intergenic transcripts that includes information on start codon, stop codon, UTRs, etc. We have our transcriptome from the long-read RNA-seq data and I aligned Ribo-seq to this new transcriptome using bowtie2. So now I have the bam files and the annotation file. I tried to run the workflow of riboWaltz but I failed. When I tried to define P-site and I got this ERROR.

`> psite_offset <- psite(reads_list, flanking = 6, extremity = "auto")

processing SRR14890805.LongRead.sort
Warning: no non-missing arguments to max; returning -InfWarning: no non-missing arguments to max; returning -InfError in if (extremity == "auto" & ((best_from3_tab[, perc] > best_from5_tab[,  : 
  argument is of length zero` 

I am kind of confused about this ERROR and have no idea how to figure it out. Could you please look into it? Many thanks for any suggestions!

Cheers,
Dongxu

**Comment by fabiolauria** [comment]
Hi Dongxu.
I would guess the error you are reporting is related to low amounts of reads - of specific length maybe - that make the _max_ function within _psite_offset_ not working as expected. Not 100% sure. In fact, I think I already faced the same error in the past but I cannot tell for sure the reason behind it and its solution.
I would need the input of the function to run it step by step (at least reads_list[["SRR14890805"]] or a portion of it).

Best,
Fabio

**Comment by Dongxu-Zheng** [comment]
> Hi Dongxu. I would guess the error you are reporting is related to low amounts of reads - of specific length maybe - that make the _max_ function within _psite_offset_ not working as expected. Not 100% sure. In fact, I think I already faced the same error in the past but I cannot tell for sure the reason behind it and its solution. I would need the input of the function to run it step by step (at least reads_list[["SRR14890805"]] or a portion of it).
> 
> Best, Fabio

Hi Fabio,

Thanks for your quick reply. I get back to check my code. When I used bamtolist function to import bam files to R, I found the number of reads as final input is very low. I guess this is depending on the annotation file (annotation.df) I used in the analysis. Here you can see some information about the bam files

`Reading SRR14890805.LongRead.sort.bam
Input reads: 9.666 M
8.000 (< 0.001 %) reads removed: exceeding indel_threshold.
9.665 M  (99.988 %) reads removed: reference transcript IDs not found in annotation table.
0.000 M  (12.108 %) reads removed: mapping on negative strand.
Output reads: 0.001 M
Done! SRR14890805.LongRead.sort.bam has been loaded as SRR14890805.LongRead.sort`

Yes, I can share the bam file with you. But how can I share it with you? The bam file is 330M. Maybe I can share it with you via google drive or do you have any preference?

Cheers,
Dongxu

**Comment by fabiolauria** [comment]
Hi Dongxu,
there might be no need of sending the BAMs.
As you pointed out, the issue is likely due to the removal of 99.98% of the reads and the low amount kept for downstream analysis.
Maybe you should try to play a bit with the _refseq_sep_ parameter of the _bamtolist_ function and try to avoid this behavior during the acquirement of the BAM. This means more reads and hopefully no errors.

Let me know.
Fabio
