### ISSUE TITLE
Input query

### ISSUE THREAD

**Issue by beth60197** [LabTranslationalArchitectomics/riboWaltz#65]
Hi there, 

If alignment was done using STAR using --quantmode TranscriptomeSAM to get transcript BAM files. Would you recommend considering all possible transcripts in the transcript bam file given some genomic alignments may have more than one transcriptomic alignment or filtering to include either reads that only have one transcript or selecting the primary transcript for each read?

**Comment by fabiolauria** [comment]
Hi,
that really depends on you and on what you want to see. What I can tell you is that my standard procedure is to keep all transcipts , allowing multiple matches. Given this, if I move from genes to transcripts I either 1) choose one representative isoform (the best annotated or protein coding or as you wish) or 2) collapse all isoforms from the same gene, removing all but one read mapping on the very same gene position.  But, again, there are plenty of options so it's really up to you.
