### ISSUE TITLE
Error on codon_coverage

### ISSUE THREAD

**Issue by theosusanto** [LabTranslationalArchitectomics/riboWaltz#68]
Hi everyone,

I am relatively new to analyzing sequencing data.
When I called codon_coverage function, it outputs an error:
```
1. creating codon table and computing distance from start/stop codon
Error in `[.data.frame`(annotation, l_utr5 > 0 & l_cds > 0 & l_cds%%3 ==  : 
  object 'transcript' not found
```
Both annotation_dt and reads_psite_list$sampleN have transcript information on them..
Could anyone please advice on how to troubleshoot? Thank you!

**Comment by theosusanto** [comment]
I think I figured it out!
I imported a custom annotation_dt instead of running "create_annotation" function.
Originally, annotation_dt is a data.frame. Converting it into data.table solves the issue

**Comment by fabiolauria** [comment]
Hi.
Happy to hear you already figured out what to do, and thank you for using riboWaltz.

I'll close this issue but feel free to open new ones whenever you are in trouble.

Best
Fabio
