### ISSUE TITLE
Issues on codon_usage_psite: "error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names"

### ISSUE THREAD

**Issue by theosusanto** [LabTranslationalArchitectomics/riboWaltz#69]
Hi everyone,

I am having issue trying to run codon_usage_psite function, similar to what some people experienced before:
```
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... 
Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names
```
The code involved:

`example <- codon_usage_psite(reads_psite_list, annotation = annotation_dt, sample = c(UNTREATED, TREATED), fastapath = PATH/TO/GENOME/FASTA, gtfpath = PATH/TO/GTF, fasta_genome = TRUE, refseq_sep = "|")`

I used the human primary assembly fasta and gtf from GENCODE. I used the same reference for alignment with STAR, using --quantMode TranscriptomeSAM. I used the *Aligned.toTranscriptome.out.bam files to generate the reads_list, and eventually the reads_psite_list.

Could anyone please advise on how to troubleshoot this issue? Thank you so much in advance!

Best regards,
Theo

**Comment by fabiolauria** [comment]
Hi Theo,
thank you for using **riboWaltz**.
As you mentioned, this seems to be a common bottleneck for many users.

Could you please paste here a couple of sequence names from the FASTA file as well as the first rows of the GTF, of one element of reads_psite_list and of annotation_dt? As usual, my guess is that the GTF and the FASTA file are not perfectly matching if we look at the names of the chromosomes/genes/transcripts.

This way I can try to figure out what is going on.

Best,
Fabio

**Comment by theosusanto** [comment]
Hi Fabio,

Thank you again for your help!
Some excerpts from the FASTA file:

```
$ cat GRCh38.primary_assembly.genome.fa | grep ">"
>chr1 1
>chr2 2
>chr3 3
...
>chrX X
>chrY Y
>chrM MT
>GL000008.2 GL000008.2
>GL000009.2 GL000009.2
>GL000194.1 GL000194.1
...
```

And some of the first rows of GTF:
```
$ head gencode.v43.primary_assembly.basic.annotation.gtf
chr1    HAVANA  gene    11869   14409   .       +       .       gene_id "ENSG00000290825.1"; gene_type "lncRNA"; gene_name "DDX11L2"; level 2; tag "overlaps_pseudogene";
chr1    HAVANA  transcript      11869   14409   .       +       .       gene_id "ENSG00000290825.1"; transcript_id "ENST00000456328.2"; gene_type "lncRNA"; gene_name "DDX11L2"; transcript_type "lncRNA"; transcript_name "DDX11L2-202"; level 2; transcript_support_level "1"; tag "basic"; tag "Ensembl_canonical"; havana_transcript "OTTHUMT00000362751.1";
chr1    HAVANA  exon    11869   12227   .       +       .       gene_id "ENSG00000290825.1"; transcript_id "ENST00000456328.2"; gene_type "lncRNA"; gene_name "DDX11L2"; transcript_type "lncRNA"; transcript_name "DDX11L2-202"; exon_number 1; exon_id "ENSE00002234944.1"; level 2; transcript_support_level "1"; tag "basic"; tag "Ensembl_canonical"; havana_transcript "OTTHUMT00000362751.1";
chr1    HAVANA  exon    12613   12721   .       +       .       gene_id "ENSG00000290825.1"; transcript_id "ENST00000456328.2"; gene_type "lncRNA"; gene_name "DDX11L2"; transcript_type "lncRNA"; transcript_name "DDX11L2-202"; exon_number 2; exon_id "ENSE00003582793.1"; level 2; transcript_support_level "1"; tag "basic"; tag "Ensembl_canonical"; havana_transcript "OTTHUMT00000362751.1";
```

Example of reads_psite_list$UNTREATED:
                  transcript end5 psite end3 length cds_start cds_stop psite_from_start psite_from_stop psite_region
       1: ENST00000000233.10   19    31   46     28        89      631              -58            -600         5utr
       2: ENST00000000233.10   31    42   57     27        89      631              -47            -589         5utr
       3: ENST00000000233.10   39    50   67     29        89      631              -39            -581         5utr
       4: ENST00000000233.10   64    76   88     25        89      631              -13            -555         5utr
       5: ENST00000000233.10   75    87  107     33        89      631               -2            -544         5utr
...

And annotation_dt:
                transcript l_tr l_utr5 l_cds l_utr3
     1: ENST00000000233.10 1032     88   543    401
     2:  ENST00000000412.8 2450    159   834   1457
     3: ENST00000000442.11 2274    225  1272    777
     4:  ENST00000001008.6 3715    170  1380   2165
     5:  ENST00000001146.7 4556     28  1539   2989
...

Hope this is helpful!

Best regards,
Theo

**Comment by theosusanto** [comment]
Hi Fabio,

The error seems to come from these lines in codon_usage_psite():

```
for (samp in sample) {
  if (!(gsub("site", "_site_codon", site) %in% colnames(data[[samp]]))) {
      if (site == "psite" & !("p_site_codon" %in% colnames(data[[samp]]))) {
        data[[samp]] <- data[[samp]][, `:=`(p_site_codon, 
          as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
            start = data[[samp]]$psite, end = data[[samp]]$psite + 
              2)))]
      }
      if (site == "asite" & !("a_site_codon" %in% colnames(data[[samp]]))) {
        data[[samp]] <- data[[samp]][, `:=`(a_site_codon, 
          as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
            start = data[[samp]]$psite + 3, end = data[[samp]]$psite + 
              5)))]
      }
      if (site == "esite" & !("e_site_codon" %in% colnames(data[[samp]]))) {
        data[[samp]] <- data[[samp]][, `:=`(e_site_codon, 
          as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
            start = data[[samp]]$psite - 3, end = data[[samp]]$psite - 
              1)))]
      }
  }
```

When I did traceback(), this odd message comes up:

> 21: h(simpleError(msg, call))
> 20: .handleSimpleError(function (cond) 
>     .Internal(C_tryCatchHelper(addr, 1L, cond)), "subscript contains invalid names", 
>         base::quote(NULL))
> 19: stop(wmsg(...), call. = FALSE)
> **18: .subscript_error("subscript contains invalid ", what)**
> 17: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
>         allow.NAs = allow.NAs)
> 16: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
>         allow.NAs = allow.NAs)
> 15: normalizeSingleBracketSubscript(i, x, as.NSBS = TRUE)
> 14: .nextMethod(x = x, i = i)
> 13: callNextMethod()
> 12: .dropUnusedPoolElts(callNextMethod())
> 11: extractROWS(x, i)
> 10: extractROWS(x, i)
> 9: subset_along_ROWS(x, i, drop = drop)
> 8: sequences[as.character(data[[samp]]$transcript)]
> 7: sequences[as.character(data[[samp]]$transcript)]
> 6: Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
>        start = data[[samp]]$psite, end = data[[samp]]$psite + 2)
> 5: eval(jsub, SDenv, parent.frame())
> 4: eval(jsub, SDenv, parent.frame())
> 3: `[.data.table`(data[[samp]], , `:=`(p_site_codon, as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
>        start = data[[samp]]$psite, end = data[[samp]]$psite + 2))))
> 2: data[[samp]][, `:=`(p_site_codon, as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
>        start = data[[samp]]$psite, end = data[[samp]]$psite + 2)))]
> 1: codon_usage_psite(reads_psite_list, annotation = annotation_dt, 
>        sample = c("Nterm_dep_rep1_RFP_Aligned.toTranscriptome.out", 
>            "wt_dep_rep1_RFP_Aligned.toTranscriptome.out"), fastapath = "data/Try2/GRCh38.primary_assembly.genome.fa", 
>        gtfpath = "data/Try2/gencode.v43.primary_assembly.basic.annotation.gtf", 
>        fasta_genome = TRUE, refseq_sep = "|")

I hope that this can be helpful.. Thank you,
Theo

**Comment by fabiolauria** [comment]
Hi Theo,
from your previous messages, I think (hope) you should be able to get rid of the error by running 

`example <- codon_usage_psite(reads_psite_list, annotation = annotation_dt, sample = c(UNTREATED, TREATED), fastapath = PATH/TO/GENOME/FASTA, gtfpath = PATH/TO/GTF, fasta_genome = TRUE, refseq_sep = " ")`

As you can see, I set parameter _refseq_sep_ , which was previously set to "|", to " " (blank space). The reason for this is that chromosomes are named "chr1 1", "chr2 2" etc. in your FASTA file and just "chr1", "chr2" etc. in your GTF. So to discard everything which is redundant in the FASTA file, you should split the string by blank space and than keep the first element (this is what _refseq_sep_ is meant for).

Let me know if this might be the solution.

Best
Fabio

**Comment by theosusanto** [comment]
It works wonderfully, thank you!
The refseq_sep then refers to the fasta file instead of the gtf file.

Another question: is it possible to average out replicates and do a codon comparison, similar to having a nested list input in rlength_distr()? I'm trying to look at the code but unfortunately it is beyond me..

Thank you,
Theo

**Comment by angelolimeta** [comment]
Hi Fabio! I'm getting the same error even though I supply the same FASTA/GTF as i used to construct the STAR database, which I then mapped using the -quantMode TranscriptomeSAM flag. I can successfully load the data into ribowaltz, calculate p-site offsets and metagene plot but I'm having issues with this particular function.

This is the command i use to generate the STAR db:
`STAR --runMode genomeGenerate \
--runThreadN 16 \
--genomeDir /mnt/disks/disk_1/fly/Index/Fullindex/ \
--genomeFastaFiles /mnt/disks/disk_1/fly/Index/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.fa \
--sjdbGTFfile /mnt/disks/disk_1/immagina/fly/Index/Drosophila_melanogaster.BDGP6.46.113.gtf` 

And this is what I'm running in R:
`example_cu_barplot <- codon_usage_psite(
  data = reads_psite_list,
  annotation = annot_dt,
  sample = "fly",
  plot_style = "facet",
  fastapath = "../data/databases/fly/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.fa",
  gtfpath = "../data/databases/fly/Drosophila_melanogaster.BDGP6.46.113.gtf",
  fasta_genome = TRUE,
)`

Which then produces the following error and traceback:

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names
 
`21: h(simpleError(msg, call))
20: .handleSimpleError(function (cond) 
    .Internal(C_tryCatchHelper(addr, 1L, cond)), "subscript contains invalid names", 
        base::quote(NULL))
19: stop(wmsg(...), call. = FALSE)
18: .subscript_error("subscript contains invalid ", what)
17: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
        allow.NAs = allow.NAs)
16: NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
        allow.NAs = allow.NAs)
15: normalizeSingleBracketSubscript(i, x, as.NSBS = TRUE)
14: .nextMethod(x = x, i = i)
13: callNextMethod()
12: .dropUnusedPoolElts(callNextMethod())
11: extractROWS(x, i)
10: extractROWS(x, i)
9: subset_along_ROWS(x, i, drop = drop)
8: sequences[as.character(data[[samp]]$transcript)]
7: sequences[as.character(data[[samp]]$transcript)]
6: Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
       start = data[[samp]]$psite, end = data[[samp]]$psite + 2)
5: eval(jsub, SDenv, parent.frame())
4: eval(jsub, SDenv, parent.frame())
3: `[.data.table`(data[[samp]], , `:=`(p_site_codon, as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
       start = data[[samp]]$psite, end = data[[samp]]$psite + 2))))
2: data[[samp]][, `:=`(p_site_codon, as.character(Biostrings::subseq(sequences[as.character(data[[samp]]$transcript)], 
       start = data[[samp]]$psite, end = data[[samp]]$psite + 2)))]
1: codon_usage_psite(data = reads_psite_list, annotation = annot_dt, 
       sample = "fly", plot_style = "facet", fastapath = "../data/databases/fly/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.fa", 
       gtfpath = "../data/databases/fly/Drosophila_melanogaster.BDGP6.46.113.gtf", 
       fasta_genome = TRUE, )`

As you can see, I'm using the same gtf/fasta combo for the alignment and for this function in RiboWaltz but still get the error.

Any help would be appreciated!

**Comment by fabiolauria** [comment]
Hi Angelo,
did you try to play with the _refseq_sep_ parameter?

It is aimed at discarding everything which is redundant in the name of the genes in the FASTA file. This is achieved by splitting the name string by blank space or other characters and keeping the first element (what usually is reported in the GTF, even if it is derived from the same repository).

Check the discussion above or similar issues for additional details.

Let me know if this might be the solution.

Best
Fabio
