### ISSUE TITLE
Error in condon_usage_psite() when measuring a-site

### ISSUE THREAD

**Issue by theosusanto** [LabTranslationalArchitectomics/riboWaltz#70]
Hi Fabio,

I have another issue related to codon_usage_psite(). I'm interested to look into possible codon bias between my datasets, specifically at the a-site. Unfortunately, this error comes up:

```
Import genomic features from the file as a GRanges object ... OK 
Prepare the 'metadata' data frame ... OK 
Make the TxDb object ... OK 
Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  :    solving row 5757949: 'allow.nonnarrowing' is FALSE and the supplied end (267) is > refwidth
```

Could you please advise on what might be the issue? Thank you as always!

Best regards,
Theo

**Comment by fabiolauria** [comment]
Hi Theo,
from the error you reported my guess is one of the following

- there is no match between the length of the sequences in the FASTA and the length reported in the annotation
- the error is related to a P-site located at the end of the transcript so it is not possible to retrieve three additional nucleotides downstream.

I checked and in both cases you have the same error as above.
To verify the first hypothesis, you can extract line 5757949 of your _data_ file, see which is the transcript related to that line, then check the length of the same transcript in the _annotation_ data.table and in a FASTA-based data structure.

Since you mapped your reads on a genome FASTA, to retrieve the length of the transcript of interest from it you can run (hope I didn't forget any package and there are no bugs in the following chunk):

```
library(data.table)
library(GenomicFeatures)
library(Biostrings)

path_to_gtf <- "GTF_PATH"
fastapath <- "FASTA_PATH"
tr_name <- "NAME_OF_TRANSCRIPT"
refseq_sep <- " "

txdbanno <- GenomicFeatures::makeTxDbFromGFF(file = path_to_gtf,
                                                                      format = "gtf",
                                                                      dataSource = NA,
                                                                      organism = NA)

refseq_sep <- " "
temp_sequences <- Biostrings::readDNAStringSet(fastapath, format = "fasta", use.names = TRUE)
          if(length(refseq_sep) != 0){
            names(temp_sequences) <- tstrsplit(names(temp_sequences), refseq_sep, fixed = TRUE, keep = 1)[[1]]
          }
          exon <- suppressWarnings(GenomicFeatures::exonsBy(txdbanno, by = "tx", use.names = TRUE))
          exon <- as.data.table(exon[unique(names(exon))])
          sub_exon_plus <- exon[as.character(seqnames) %in% names(temp_sequences) & strand == "+"]
          sub_exon_minus <- exon[as.character(seqnames) %in% names(temp_sequences) & strand == "-"
                                 ][, new_end := Biostrings::width(temp_sequences[as.character(seqnames)]) - start + 1
                                   ][, new_start := Biostrings::width(temp_sequences[as.character(seqnames)]) - end + 1]
          
          seq_dt_plus <- sub_exon_plus[, nt_seq := "emp"
                                       ][, nt_seq := as.character(Biostrings::subseq(temp_sequences[as.character(seqnames)],
                                                                                     start = start,
                                                                                     end = end))
                                         ][, list(seq = paste(nt_seq, collapse = "")), by = group_name]
          
          revcompl_temp_sequences <- Biostrings::reverseComplement(temp_sequences)
          seq_dt_minus <- sub_exon_minus[, nt_seq := "emp"
                                         ][, nt_seq := as.character(Biostrings::subseq(revcompl_temp_sequences[as.character(seqnames)],
                                                                                       start = new_start,
                                                                                       end = new_end))
                                           ][, list(seq = paste(nt_seq, collapse = "")), by = group_name]
          
          sequences <- Biostrings::DNAStringSet(c(seq_dt_plus$seq, seq_dt_minus$seq))
          names(sequences) <- c(unique(sub_exon_plus$group_name), unique(sub_exon_minus$group_name))

Biostrings::width(temp_sequences[tr_name ]) 
```

At he same time, you can also verify the second hypothesis by checking if the P-site position reported in line 5757949 of your _data_ file is close to the end of the transcript (i.e. its coordinate is almost equal to the length of the transcript).

Let me know how it is going.

Best
Fabio

**Comment by theosusanto** [comment]
Hi Fabio,

I'm looking at a smaller dataset to troubleshoot, and the error is now at row 1796812. Based on that:

I got the transcript name from a given line in reads_psite_list.
```
> reads_psite_list$Sample1_RFP_1[1796812,]
          transcript end5 psite end3 length cds_start cds_stop psite_from_start psite_from_stop psite_region
1: ENST00000294168.8 2009  2021 2023     15       109     1977             1912              44         3utr
```

Then I checked the length of transcript in annotation data.table:
```
> annotation_dt[annotation_dt$transcript == "ENST00000294168.8"]
          transcript l_tr l_utr5 l_cds l_utr3
1: ENST00000294168.8 2023    108  1869     46
```
Then I ran the code you gave me, changing Biostrings::width(temp_sequences[tr_name ]) to Biostrings::width(sequences[tr_name ])
```
> Biostrings::width(sequences[ENST00000294168.8])
[1] 2023
```

The length of transcript matches in the annotation data.table and the fasta file.
Second hypothesis is correct, as the issue is related to p-site 2 nucleotides before the end of the transcript.

Temporarily I could subset only the cds and 5'utr, but it might be better if such reads that can be ignored when running the function.. Thank you again for your help!

Best regards,
Theo

**Comment by fabiolauria** [comment]
Hi Theo,
thank for the report and sorry for this inconvenience.
Concerning the modification you propose, you are absolutely right and I already added it to my to-do list.

I'm going to close this issue and if you need more help, feel free to open another one.

Best
Fabio
