### ISSUE TITLE
Q: Get the Codon Usage Index Table 

### ISSUE THREAD

**Issue by chenghongdeng** [LabTranslationalArchitectomics/riboWaltz#80]
Hi Fabio, 

Firstly, I would say I have RiboWaltz, it is very useful for my research. 

I am able to get command working. Right now I have the figure for codon usage. However, my question is: If is possible for me to get the actually table which contain the codon usage index for each individual codon. 

Thank you
Chenghong

**Comment by fabiolauria** [comment]
Hi Chenghong,
thank you for using riboWaltz.

Theoretically, the _codon_usage_psite_ fuction, as all the others from the tools, return as output a list. In this list, you can find the plot, the data to manually build the plot with personalized scales and options and the data - raw or normalized - the plot is based on. You can find [here](https://github.com/LabTranslationalArchitectomics/riboWaltz?tab=readme-ov-file#list-of-outputs) more details about the canonical output of every function.

If the data you are looking for are not in these tables, just let me know.

Best
Fabio

**Comment by chenghongdeng** [comment]
Hi Fabio, 

Thanks for your responses. I will look into that.

**Comment by fabiolauria** [comment]
Good!
I'll close this issue then. Feel free to reopen it if needed.

Best
Fabio
