### ISSUE TITLE
If I aim to find the transcript alignment events which belong to 0_frame in CDS region, could you share me the solution? 

### ISSUE THREAD

**Issue by punching-samuel** [LabTranslationalArchitectomics/riboWaltz#84]
According to the function: frame_psite, I can get the visualized results like the following plot:
<img width="312" alt="截屏2024-12-24 17 06 26" src="https://github.com/user-attachments/assets/370db1cf-5d71-4687-8843-deba6c005738" />
But If I only want to get the alignment events(RPF reads or aligned events) which belong to 0_frame in CDS region, what can I do for that result.

**Comment by fabiolauria** [comment]
Hi there.
If you want to subset the original dataset by retriving only those reads mapping in frame 0, you cannot do that using _frame_psite_. But for each sample you can easily compute the frame of each psite and than filter the data table keeping only those with frame 0 and mapping on the CDS. Something like this for one hypothehical "sample1" (choose the correct names for the data structure and the sample): 

```
list_samples[["samp1"]][, frame := psite_from_start %% 3]
list_samples_filtered[["samp1"]] <- list_samples[["samp1"]][frame == 0 & psite_region == "cds"]
```

Obviously, to extend this to all samples you have to put this chunk in a for loop and organise the code accordingly.

Best
Fabio

**Comment by punching-samuel** [comment]
I have a related question, if you don't mind. I would like to extract entries from the BAM file based on list_samples_filtered, which is the filtered table. Would you be able to provide a solution for this? Thank you in advance!

**Comment by punching-samuel** [comment]
I have a related question, if you don't mind. I would like to extract
entries from the BAM file based on list_samples_filtered, which is the
filtered table. Would you be able to provide a solution for this? Thank you
in advance!


Looking forward to your response.

Best regards,

Sen Yang
Shanghai Immune Therapy Institute, Renji Hospital
Shanghai Jiao Tong University School of Medicine
Shanghai, China

fabiolauria ***@***.***> 于2024年12月24日周二 20:50写道：

**Comment by fabiolauria** [comment]
Sorry, I'm not sure I understand what you would like to do. Do you mean that, after selecting the reads from list_samples_filtered, you want to go back to the original BAM and filter that file accordingly? If this is the case, unfortunately you cannot do this with RiboWaltz. It doesn't keep track of read'ID so it's not possibile to go back to them. You would have to do it manually with your own functions (feel free tò take and modify riboWaltz's ones).

Let me know.
Fabio

**Comment by punching-samuel** [comment]
[image: 截屏2024-12-25 00.08.26.png]

You have understood my question perfectly. I would like to extract RPF
reads that are in the 0_frame, and I was thinking about using the
reads_psite_list_filtered table to select the corresponding alignment
entries from the BAM file. After that, I plan to convert them back to FASTQ
format using samtools, as I understand that 0_frame reads may be relatively
more reliable. My intention is to use these reads for further analysis.

Do you have any suggestions or advice on this approach? Additionally, when
performing analyses such as generating metaprofiles, how do you typically
handle 2_frame and 3_frame entries? Would you include them in your
observations, or do you have specific criteria to filter them out?

I am a beginner in transcriptome and would greatly appreciate your
guidance. Thank you very much for your help!


Best regards,

Sen Yang

fabiolauria ***@***.***> 于2024年12月25日周三 00:02写道：

**Comment by punching-samuel** [comment]
You have understood my question perfectly. I would like to extract RPF reads that are in the 0_frame, and I was thinking about using the reads_psite_list_filtered table to select the corresponding alignment entries from the BAM file. After that, I plan to convert them back to FASTQ format using samtools, as I understand that 0_frame reads may be relatively more reliable. My intention is to use these reads for further analysis.

Do you have any suggestions or advice on this approach? Additionally, when performing analyses such as generating metaprofiles, how do you typically handle 2_frame and 3_frame entries? Would you include them in your observations, or do you have specific criteria to filter them out?

I am a beginner in transcriptome and would greatly appreciate your guidance. Thank you very much for your help!

![image](https://github.com/user-attachments/assets/66bce5a7-9009-4449-b71f-d35613e2c134)


> Sorry, I'm not sure I understand what you would like to do. Do you mean that, after selecting the reads from list_samples_filtered, you want to go back to the original BAM and filter that file accordingly? If this is the case, unfortunately you cannot do this with RiboWaltz. It doesn't keep track of read'ID so it's not possibile to go back to them. You would have to do it manually with your own functions (feel free tò take and modify riboWaltz's ones).
> 
> Let me know. Fabio

**Comment by fabiolauria** [comment]
To answer both questions: my suggestion and what is usually done is to keep all reads, in frame and not in frame (if the experiment went well, otherwise there are other problems). There are no scenarios where riboseq data can give you only in-frame reads, and remove what is not in frame would lead to suspicious results. Plus, keep in mind that "in frame reads" depend on the tool you are using, and that in any case for non-positional analysis the exact position and frame of reads is not of any interest.
