### ISSUE TITLE
"100% reads removed: mapping on the negative strand" caused by discordant transcript IDs.

### ISSUE THREAD

**Issue by mt1022** [LabTranslationalArchitectomics/riboWaltz#9]
Thanks for developing this helpful toolkit. I found the message printed by [this section](https://github.com/LabTranslationalArchitectomics/riboWaltz/blob/5aad01774098ed1cc5796686c9ac254d71a64e61/R/combine_bam.R#L92-L99) of code is not very helpful for some special cases:
```
    if(transcript_align == TRUE | transcript_align == T){
      nreads <- nrow(dt)
      cat(sprintf("reads (total): %s M\n", format(round((nreads / 1e+06), 2), nsmall = 2)))
      dt <- dt[as.character(transcript) %in% as.character(annotation$transcript) & strand == "+"]
      cat(sprintf("%s M  (%s %%) reads removed: mapping on the negative strand\n", 
                  format(round((nreads - nrow(dt))/ 1e+06, 2), nsmall = 2), 
                  format(round(((nreads - nrow(dt))/nreads) * 100, 2), nsmall = 2) ))
    }

```
For example, I have ensembl transcript id in annotation files like **`ENSMUST00000195858`**. But the bam file has transcript ids with version numbers like  **`ENSMUST00000195858.1`**. This will caus all reads being filtered out with a message like "100% reads removed: mapping on the negative strand". However, the true reason is that the transcript ids don't match.

This sounds really critical but I hope you could consider this. A possible way is do this fitering in two steps and print more helpful message for users to debug.

**Comment by fabiolauria** [comment]
Hi,
thank you for using riboWaltz and for reporting the issue.
I'm just wondering how come you have such a discrepancy between the transcript IDs in the annotation and the BAM file.
This issue shouldn't arise neither i) using Bowtie directly on a transcriptome FASTA and the corresponding (i.e. downloaded from the same repository) GTF file in downstream analyses, where the transcript IDs are supposed to match, nor ii) using STAR on a standard FASTA of chromosome sequences where an annotation file is required, and the same GTF is given as input to the _create_annotation_ function.
Which tool did you use for aligning your data and where you get the FASTA and GTF you are using? Or are you employing txdb objects instead?

To solve the problem, I think I'll split _bamtolist_ moving the filtering step to a dedicated function allowing, if needed, the removal of the version of the transcript from the IDs in the BAM file (assuming the transcript IDs would match after this additional step).

I really appreciate your tip about the two-steps filtering. Thus, if the change in the code described above is not what you meant, I ask you to elaborate the concept a bit (e.g. what the steps should be)  so I might try and modify the script in line with your suggestions.

Bests,
Fabio

**Comment by mt1022** [comment]
Hi, 
Thanks for the timely response.

*how come you have such a discrepancy* I downloaded the transcript sequences and gtf file both from [here](http://www.ensembl.org/info/data/ftp/index.html). The gtf file was supplied to `create_annotation`. The reads were mapped to `Mus_musculus.GRCm38.cdna.all.fa.gz` with bowtie2 and the transcript ids in the final bam file contains version numbers.

My suggestion is more like the simple code below:
```
dt <- dt[as.character(transcript) %in% as.character(annotation$transcript)]
cat('xx% reads are removed because their refence sequences are not included in annotation table')
nreads <- nrow(dt)
dt <- dt[strand == "+"]
...
```
i.e, tell the use how many reads were removed due to `as.character(transcript) %in% as.character(annotation$transcript)` and how many reads were removed due to `strand == "+"`.  I don't think it is necessary for you to fix the ids. There are other ways to produce the same error. For example, I once provided a human gtf for mouse data and got the same error. I think a message telling user how many reads are removed due to  transcripts not found in annotation data would be enough. I hope I have made my points clear :).

Bests,
Hong

**Comment by fabiolauria** [comment]
Hi Hong,
thank you for the clarifications.

> I downloaded the transcript sequences and gtf file both from here. 

I usually download the FASTA and GTF from GENCODE, where the two files refer to the mRNAa through the same IDs (that include the version of the transcripts). Thus, I didn't account for potential discrepancies in different repositories, but I will now.

> telling user how many reads are removed due to transcripts not found in annotation data.

This is undoubtedly a good idea, I will add a dedicated message in a while.

> I don't think it is necessary for you to fix the ids.

I thought to this option to avoid the user to modify either the FASTA or the GTF so that the IDs match (assuming them to refer to the same repository/release/organism).

I'll proceed with the last point as soon as possible. Meanwhile I am going to close the thread. 
If other issues arise, please let me know.

Bests,
Fabio
